<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>Coldfusion Cfscript Language</string>
    <key>fileTypes</key>
    <array>
    </array>
    <key>firstLineMatch</key>
    <string></string>
    <key>foldingStartMarker</key>
    <string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\}</string>
    <key>keyEquivalent</key>
    <string></string>
    <key>name</key>
    <string>cfscript</string>
    <key>patterns</key>
    <array>


        <dict>
            <key>include</key>
            <string>#cfscript</string>
        </dict>
    </array>

    <key>repository</key>
    <dict>

        <!-- functions -->
        <key>functions</key>
        <dict>
            <key>begin</key>
                <string>(?x)^\s*
                    (?:
                        (?: # optional access-control modifier and return-type
                            (?:(?:\b(private|package|public|remote))\b\s+)+\s* # access-control.modifier
                            (?:\b
                                (void)
                                |
                                (any|array|binary|boolean|component|date|guid|numeric|query|string|struct|xml|uuid) # return-type.primitive
                                |
                                ([A-Za-z0-9_\.$]+) #return-type component/object (may need additional tokens)
                            )?
                        )?
                    )
                    \s*
                    (function) # storage.function
                    \s+
                    (?:
                        (init) # entity.name.function.contructor
                        |
                        (\w+) # entity.name.function
                    )
                    \s*
                </string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.access-control.cfscript</string>
                </dict>
                <key>2</key>
                 <dict>
                    <key>name</key>
                    <string>storage.type.return-type.void.cfscript</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.return-type.primitive.cfscript</string>
                </dict>
                <key>4</key>
                 <dict>
                    <key>name</key>
                    <string>storage.type.return-type.object.cfscript</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.function.cfscript</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.constructor.cfscript</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cfscript</string>
                </dict>
                <!-- <key>8</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.function-parameters.begin.cfscript</string>
                </dict> -->
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.function-parameters.end.cfscript</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.definition.function.cfscript</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.definition.seperator.parameter.cfscript</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#cfscript-code</string>
                </dict>
            </array>
        </dict>
        <!-- /functions -->




        <key>cfscript</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#cfscript-code</string>
                </dict>
            </array>
        </dict>

        <key>cfscript-code</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sql-code</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#variables</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#storage-types</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#comments</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#keywords</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#function-call</string>
                </dict>
            </array>
        </dict>
        <!-- storage types -->
        <key>storage-types</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(var)\b</string>
                    <key>name</key>
                    <string>storage.modifier.var.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(string|date|struct|array|void|binary|numeric|boolean|query|xml|uuid|any)(?:\[\s*\])*\b</string>
                    <key>name</key>
                    <string>storage.type.primitive.cfscript</string>
                </dict>
            </array>
        </dict>
        <!-- constants -->
        <key>constants</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b([A-Z][A-Z0-9_\.]+)\b</string>
                    <key>name</key>
                    <string>constant.other.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(true|false|null)\b</string>
                    <key>name</key>
                    <string>constant.language.cfscript</string>
                </dict>
            </array>
        </dict>
        <!-- comments -->
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <!-- comment block /** -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.cfscript</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>/\*\*/</string>
                    <key>name</key>
                    <string>comment.block.empty.cfscript</string>
                </dict>
                <!-- as javadoc for cfscript annotations -->
                <dict>
                    <key>include</key>
                    <string>text.html.javadoc</string>
                </dict>
                <!-- block comments (bellow) -->
                <dict>
                    <key>include</key>
                    <string>#comment-block</string>
                </dict>
                <!-- double-slash comment -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.cfscript</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(//).*$\n?</string>
                    <key>name</key>
                    <string>comment.line.double-slash.cfscript</string>
                </dict>
            </array>
        </dict>
        <!-- comment-block /* -->
        <key>comment-block</key>
        <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cfscript</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.cfscript</string>
        </dict>
        <!-- /comments -->
        <!-- strings -->
        <key>strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#string-quoted-double</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-quoted-single</string>
                </dict>
            </array>
        </dict>
        <key>string-quoted-double</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.cfscript</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.cfscript</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.cfscript</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_hash</string>
                </dict>
            </array>
        </dict>
        <key>string-quoted-single</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.cfscript</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.cfscript</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.cfscript</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_hash</string>
                </dict>
            </array>
        </dict>
        <!-- /strings -->

        <!-- keywords -->
        <key>keywords</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(new)\b</string>
                    <key>name</key>
                    <string>keyword.other.new.cfml</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(try|catch|throw)\b</string>
                    <key>name</key>
                    <string>keyword.control.catch-exception.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(return|break|do|while|for|switch|case|default|if|else)\b</string>
                    <key>name</key>
                    <string>keyword.control.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
                    <key>name</key>
                    <string>keyword.operator.comparison.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(?i:EQ|NEQ|LT|LTE|GT|GTE|AND|IS|NOT)\b</string>
                    <key>name</key>
                    <string>keyword.operator.other.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\-=|\+=|\*=|\/=|%=)</string>
                    <key>name</key>
                    <string>keyword.operator.other.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(&amp;=)</string>
                    <key>name</key>
                    <string>keyword.operator.concat.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(=)</string>
                    <key>name</key>
                    <string>keyword.operator.assignment.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\-\-|\+\+)</string>
                    <key>name</key>
                    <string>keyword.operator.increment-decrement.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\-|\+|\*|\/|%)</string>
                    <key>name</key>
                    <string>keyword.operator.arithmetic.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(!|&amp;&amp;|\|\|)</string>
                    <key>name</key>
                    <string>keyword.operator.logical.cfscript</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>;</string>
                    <key>name</key>
                    <string>punctuation.terminator.cfscript</string>
                </dict>
            </array>
        </dict>
        <!-- / keywords -->

        <!-- function-call -->
        <!-- TODO: add all language functions -->
        <key>function-call</key>
        <dict>
            <key>begin</key>
            <string>(?:(\w+))(\()</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.function.cfscript</string>
                </dict>
                <!-- <key>3</key>
                <dict>
                    <key>name</key>
                    <string>support.function.cfml</string>
                </dict> -->
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.function-parameters.begin.cfscript</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.function-parameters.end.cfscript</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.cfscript</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.definition.seperator.parameter.cfscript</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#cfscript-code</string>
                </dict>
            </array>
        </dict>
        <!-- /function-call -->
        <!-- nest_hash -->
        <key>nest_hash</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>##</string>
                    <key>name</key>
                    <string>string.escaped.hash.cfscript</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(#)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.hash.begin.cfscript</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(#)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.hash.end.cfscript</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>source.cfscript.embedded.cfscript</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#function-call</string>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\w+</string>
                            <key>name</key>
                            <string>variable.other.interpolated.cfscript</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <!-- /nest_hash -->
        <!-- variables -->
        <key>variables</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(this)\b</string>
                    <key>name</key>
                    <string>variable.language.cfscript</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\b(this|super)\.</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.language.cfscript</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(\w+)\b</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.cfscript</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <!-- /variables -->

        <!-- sql -->
        <key>sql-code</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>\.((?i:setsql))\(\s*["|']</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.function.setsql.cfscripts</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(["|']\s*\))</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.parenthesis.end.cfscript</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>source.sql.embedded.cfscript</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.sql</string>
                        </dict>
                    </array>

                </dict>
            </array>
        </dict>


    </dict>

    <key>scopeName</key>
    <string>source.cfscript</string>
    <key>uuid</key>
    <string>D5324EE0-4226-11E1-B86C-0800200C9A66</string>
</dict>
</plist>
