<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>cfc</string>
    </array>
    <key>firstLineMatch</key>
    <string></string>
    <key>foldingStartMarker</key>
    <string></string>
    <key>foldingStopMarker</key>
    <string></string>
    <key>keyEquivalent</key>
    <string></string>
    <key>name</key>
    <string>ColdFusion Component</string>
    <key>patterns</key>
    <array>

        <!-- TAG BASED CFCOMPONENT -->
        <dict>
            <key>begin</key>
            <string>(?:^\s+)?(&lt;)((?i:cfcomponent))(?![^&gt;]*/&gt;)</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>meta.tag.block.cf.component.cfml</string>
                </dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.cf.begin.cfml</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.cf.component.cfml</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.cf.end.cfml</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)((?i:cfcomponent))(&gt;)(?:\s*\n)?</string>
            <key>contentName</key>
            <string>text.html.cfm.embedded.cfml</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=cfcomponent)\s</string>
                    <key>end</key>
                    <string>(?=&gt;)</string>
                    <key>name</key>
                    <string>meta.tag.block.cf.component.cfml</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#tag-stuff</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.block.cf.component.cfml</string>
                        </dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.cf.end.cfml</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?=&lt;/(?i:cfcomponent))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>text.html.cfm</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>

        <dict>
            <key>include</key>
            <string>#cfcomments</string>
        </dict>

        <dict>
            <key>include</key>
            <string>source.cfscript</string>
        </dict>
    </array>

    <key>repository</key>
    <dict>

        <key>cfcomments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>&lt;!---.*---&gt;</string>
                    <key>name</key>
                    <string>comment.line.cfml</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>&lt;!---</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.cfml</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>---&gt;</string>
                    <key>name</key>
                    <string>comment.block.cfml</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#cfcomments</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>

        <key>tag-stuff</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-generic-attribute</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-double-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-single-quoted</string>
                </dict>
            </array>
        </dict>

        <key>tag-generic-attribute</key>
        <dict>
            <key>match</key>
            <string>\b([a-zA-Z\-:]+)</string>
            <key>name</key>
            <string>entity.other.attribute-name.html</string>
        </dict>
        <key>string-double-quoted</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>
        <key>string-single-quoted</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>

        <key>entities</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entity.html</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entity.html</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
                    <key>name</key>
                    <string>constant.character.entity.html</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>&amp;</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-ampersand.html</string>
                </dict>
            </array>
        </dict>
    </dict>


    <key>scopeName</key>
    <string>source.cfscript.cfc</string>

    <key>uuid</key>
    <string>B7AC5320-4226-11E1-B86C-0800200C9A66</string>
</dict>
</plist>
