<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfm</string>
		<string>cfml</string>
	</array>
	<key>firstLineMatch</key>
	<string></string>
	<key>foldingStartMarker</key>
	<string></string>
	<key>foldingStopMarker</key>
	<string></string>
	<key>keyEquivalent</key>
	<string></string>
	<key>name</key>
	<string>ColdFusion</string>
	<key>patterns</key>
	<array>

		<!-- CFSCRIPT -->
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:cfscript))(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cfscript.cfml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.cfml</string>
				</dict>
			</dict>

			<key>end</key>
			<string>(&lt;/)((?i:cfscript))(&gt;)(?:\s*\n)?</string>
			<key>name</key>
			<string>source.cfscript.embedded.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cfscript</string>
				</dict>
			</array>
		</dict>


		<!-- CFFUNCTION -->
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:cffunction))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cffunction.cfml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)((?i:cffunction))(&gt;)(?:\s*\n)?</string>
			<key>name</key>
			<string>text.html.cfm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-name-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.cfml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&lt;/(?i:cffunction))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.cfm</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>


		<!-- CFQUERY -->
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:cfquery))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.start.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cfquery.cfml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)((?i:cfquery))(&gt;)(?:\s*\n)?</string>
			<key>name</key>
			<string>source.sql.embedded.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.cfml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&lt;/(?i:cfquery))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>

		<!-- TODO: CFSET -->

		<dict>
			<key>include</key>
			<string>#cfcomment</string>
		</dict>

		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>

	<key>repository</key>
	<dict>





		<!-- for Symbol List cffunction -->
		<key>tag-name-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(name)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.name.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.name.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.cfml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.name.cfml</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.cfml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.cfml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.cfml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.name.cfml</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.cfml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.cfml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>



		<key>cfcomment</key>
		<dict>
			<key>begin</key>
			<string>&lt;!---</string>
			<key>end</key>
			<string>---&gt;</string>
			<key>name</key>
			<!-- <string>comment.block.html</string> -->
			<!-- this is set to line to differentiate htmlcomment/cfcomment -->
			<string>comment.line.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cfcomment</string>
				</dict>
			</array>
		</dict>

		<!-- this tag-stuff is just for coloring tag attributes -->
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>

		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>

		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
	</dict>

	<key>scopeName</key>
	<string>text.html.cfm</string>

	<key>uuid</key>
	<string>C48DE6D0-4226-11E1-B86C-0800200C9A66</string>
</dict>
</plist>
