import cf9
class tags(cf9.tags):
	def __init__(self):
		super(tags, self).__init__()
		self.completions['cfapplication'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("loginstorage\t@loginstorage", "loginstorage=\"$1\"$0"),
				("loginstorage=\"cookie\"\tloginstorage", "loginstorage=\"${1:cookie}\"$0"),
				("loginstorage=\"session\"\tloginstorage", "loginstorage=\"${1:session}\"$0"),
				("clientmanagement\t@clientmanagement", "clientmanagement=\"$1\"$0"),
				("clientmanagement=\"true\"\tclientmanagement", "clientmanagement=\"${1:true}\"$0"),
				("clientmanagement=\"false\"\tclientmanagement", "clientmanagement=\"${1:false}\"$0"),
				("clientstorage\t@clientstorage", "clientstorage=\"$1\"$0"),
				("clientstorage=\"cookie\"\tclientstorage", "clientstorage=\"${1:cookie}\"$0"),
				("clientstorage=\"registry\"\tclientstorage", "clientstorage=\"${1:registry}\"$0"),
				("clientstorage=\"datasource_name\"\tclientstorage", "clientstorage=\"${1:datasource_name}\"$0"),
				("setclientcookies\t@setclientcookies", "setclientcookies=\"$1\"$0"),
				("setclientcookies=\"true\"\tsetclientcookies", "setclientcookies=\"${1:true}\"$0"),
				("setclientcookies=\"false\"\tsetclientcookies", "setclientcookies=\"${1:false}\"$0"),
				("sessionmanagement\t@sessionmanagement", "sessionmanagement=\"$1\"$0"),
				("sessionmanagement=\"true\"\tsessionmanagement", "sessionmanagement=\"${1:true}\"$0"),
				("sessionmanagement=\"false\"\tsessionmanagement", "sessionmanagement=\"${1:false}\"$0"),
				("sessiontimeout\t@sessiontimeout", "sessiontimeout=\"$1\"$0"),
				("applicationtimeout\t@applicationtimeout", "applicationtimeout=\"$1\"$0"),
				("setdomaincookies\t@setdomaincookies", "setdomaincookies=\"$1\"$0"),
				("setdomaincookies=\"true\"\tsetdomaincookies", "setdomaincookies=\"${1:true}\"$0"),
				("setdomaincookies=\"false\"\tsetdomaincookies", "setdomaincookies=\"${1:false}\"$0"),
				("scriptprotect\t@scriptprotect", "scriptprotect=\"$1\"$0"),
				("scriptprotect=\"none\"\tscriptprotect", "scriptprotect=\"${1:none}\"$0"),
				("scriptprotect=\"all\"\tscriptprotect", "scriptprotect=\"${1:all}\"$0"),
				("scriptprotect=\"form\"\tscriptprotect", "scriptprotect=\"${1:form}\"$0"),
				("scriptprotect=\"url\"\tscriptprotect", "scriptprotect=\"${1:url}\"$0"),
				("scriptprotect=\"cookie\"\tscriptprotect", "scriptprotect=\"${1:cookie}\"$0"),
				("scriptprotect=\"cgi\"\tscriptprotect", "scriptprotect=\"${1:cgi}\"$0"),
				("scriptprotect=\"form,url\"\tscriptprotect", "scriptprotect=\"${1:form,url}\"$0"),
				("scriptprotect=\"form,url,cookie\"\tscriptprotect", "scriptprotect=\"${1:form,url,cookie}\"$0"),
				("scriptprotect=\"form,url,cookie,cgi\"\tscriptprotect", "scriptprotect=\"${1:form,url,cookie,cgi}\"$0"),
				("securejsonprefix\t@securejsonprefix", "securejsonprefix=\"$1\"$0"),
				("securejsonprefix=\"true\"\tsecurejsonprefix", "securejsonprefix=\"${1:true}\"$0"),
				("securejsonprefix=\"false\"\tsecurejsonprefix", "securejsonprefix=\"${1:false}\"$0"),
				("securejson\t@securejson", "securejson=\"$1\"$0"),
				("securejson=\"true\"\tsecurejson", "securejson=\"${1:true}\"$0"),
				("securejson=\"false\"\tsecurejson", "securejson=\"${1:false}\"$0")
			],
			'attributes': [
				"loginstorage",
				"setclientcookies",
				"name",
				"scriptprotect",
				"sessionmanagement",
				"securejson",
				"setdomaincookies",
				"clientmanagement",
				"sessiontimeout",
				"securejsonprefix",
				"applicationtimeout",
				"clientstorage"
			]
		}
		self.completions['cfcache'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"cache\"\taction", "action=\"${1:cache}\"$0"),
				("action=\"flush\"\taction", "action=\"${1:flush}\"$0"),
				("action=\"clientcache\"\taction", "action=\"${1:clientcache}\"$0"),
				("action=\"servercache\"\taction", "action=\"${1:servercache}\"$0"),
				("action=\"optimal\"\taction", "action=\"${1:optimal}\"$0"),
				("directory\t@directory", "directory=\"$1\"$0"),
				("timespan\t@timespan", "timespan=\"$1\"$0"),
				("expireurl\t@expireurl", "expireurl=\"$1\"$0"),
				("username\t@username", "username=\"$1\"$0"),
				("password\t@password", "password=\"$1\"$0"),
				("port\t@port", "port=\"$1\"$0"),
				("protocol\t@protocol", "protocol=\"$1\"$0"),
				("protocol=\"http://\"\tprotocol", "protocol=\"${1:http://}\"$0"),
				("protocol=\"https://\"\tprotocol", "protocol=\"${1:https://}\"$0")
			],
			'attributes': [
				"directory",
				"port",
				"username",
				"protocol",
				"expireurl",
				"action",
				"password",
				"timespan"
			]
		}
		self.completions['cfcollection'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"categorylist\"\taction", "action=\"${1:categorylist}\"$0"),
				("action=\"create\"\taction", "action=\"${1:create}\"$0"),
				("action=\"delete\"\taction", "action=\"${1:delete}\"$0"),
				("action=\"optimize\"\taction", "action=\"${1:optimize}\"$0"),
				("action=\"list\"\taction", "action=\"${1:list}\"$0"),
				("action=\"map\"\taction", "action=\"${1:map}\"$0"),
				("action=\"repair\"\taction", "action=\"${1:repair}\"$0"),
				("collection\t@collection", "collection=\"$1\"$0"),
				("path\t@path", "path=\"$1\"$0"),
				("language\t@language", "language=\"$1\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("categories\t@categories", "categories=\"$1\"$0"),
				("categories=\"true\"\tcategories", "categories=\"${1:true}\"$0"),
				("categories=\"false\"\tcategories", "categories=\"${1:false}\"$0")
			],
			'attributes': [
				"categories",
				"path",
				"name",
				"action",
				"language",
				"collection"
			]
		}
		self.completions['cfcomponent'] = {
			'completions': [
				("extends\t@extends", "extends=\"$1\"$0"),
				("implements\t@implements", "implements=\"$1\"$0"),
				("output\t@output", "output=\"$1\"$0"),
				("output=\"true\"\toutput", "output=\"${1:true}\"$0"),
				("output=\"false\"\toutput", "output=\"${1:false}\"$0"),
				("displayname\t@displayname", "displayname=\"$1\"$0"),
				("hint\t@hint", "hint=\"$1\"$0"),
				("style\t@style", "style=\"$1\"$0"),
				("style=\"rpc\"\tstyle", "style=\"${1:rpc}\"$0"),
				("style=\"document\"\tstyle", "style=\"${1:document}\"$0"),
				("namespace\t@namespace", "namespace=\"$1\"$0"),
				("serviceportname\t@serviceportname", "serviceportname=\"$1\"$0"),
				("porttypename\t@porttypename", "porttypename=\"$1\"$0"),
				("bindingname\t@bindingname", "bindingname=\"$1\"$0"),
				("wsdlfile\t@wsdlfile", "wsdlfile=\"$1\"$0"),
				("serviceaddress\t@serviceaddress", "serviceaddress=\"$1\"$0")
			],
			'attributes': [
				"style",
				"wsdlfile",
				"displayname",
				"implements",
				"hint",
				"porttypename",
				"extends",
				"output",
				"serviceaddress",
				"namespace",
				"bindingname",
				"serviceportname"
			]
		}
		self.completions['cfcookie'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("value\t@value", "value=\"$1\"$0"),
				("expires\t@expires", "expires=\"$1\"$0"),
				("secure\t@secure", "secure=\"$1\"$0"),
				("secure=\"true\"\tsecure", "secure=\"${1:true}\"$0"),
				("secure=\"false\"\tsecure", "secure=\"${1:false}\"$0"),
				("path\t@path", "path=\"$1\"$0"),
				("domain\t@domain", "domain=\"$1\"$0")
			],
			'attributes': [
				"path",
				"expires",
				"name",
				"domain",
				"secure",
				"value"
			]
		}
		self.completions['cfdirectory'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"list\"\taction", "action=\"${1:list}\"$0"),
				("action=\"create\"\taction", "action=\"${1:create}\"$0"),
				("action=\"delete\"\taction", "action=\"${1:delete}\"$0"),
				("action=\"rename\"\taction", "action=\"${1:rename}\"$0"),
				("directory\t@directory", "directory=\"$1\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("filter\t@filter", "filter=\"$1\"$0"),
				("mode\t@mode", "mode=\"$1\"$0"),
				("sort\t@sort", "sort=\"$1\"$0"),
				("sort=\"asc\"\tsort", "sort=\"${1:asc}\"$0"),
				("sort=\"desc\"\tsort", "sort=\"${1:desc}\"$0"),
				("newdirectory\t@newdirectory", "newdirectory=\"$1\"$0"),
				("recurse\t@recurse", "recurse=\"$1\"$0"),
				("recurse=\"true\"\trecurse", "recurse=\"${1:true}\"$0"),
				("recurse=\"false\"\trecurse", "recurse=\"${1:false}\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"dir\"\ttype", "type=\"${1:dir}\"$0"),
				("type=\"file\"\ttype", "type=\"${1:file}\"$0"),
				("type=\"all\"\ttype", "type=\"${1:all}\"$0"),
				("listinfo\t@listinfo", "listinfo=\"$1\"$0"),
				("listinfo=\"name\"\tlistinfo", "listinfo=\"${1:name}\"$0"),
				("listinfo=\"all\"\tlistinfo", "listinfo=\"${1:all}\"$0")
			],
			'attributes': [
				"directory",
				"sort",
				"name",
				"recurse",
				"listinfo",
				"mode",
				"action",
				"type",
				"newdirectory",
				"filter"
			]
		}
		self.completions['cfdocument'] = {
			'completions': [
				("format\t@format", "format=\"$1\"$0"),
				("format=\"PDF\"\tformat", "format=\"${1:PDF}\"$0"),
				("format=\"FlashPaper\"\tformat", "format=\"${1:FlashPaper}\"$0"),
				("filename\t@filename", "filename=\"$1\"$0"),
				("overwrite\t@overwrite", "overwrite=\"$1\"$0"),
				("overwrite=\"true\"\toverwrite", "overwrite=\"${1:true}\"$0"),
				("overwrite=\"false\"\toverwrite", "overwrite=\"${1:false}\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("pagetype\t@pagetype", "pagetype=\"$1\"$0"),
				("pagetype=\"legal\"\tpagetype", "pagetype=\"${1:legal}\"$0"),
				("pagetype=\"letter\"\tpagetype", "pagetype=\"${1:letter}\"$0"),
				("pagetype=\"A4\"\tpagetype", "pagetype=\"${1:A4}\"$0"),
				("pagetype=\"A5\"\tpagetype", "pagetype=\"${1:A5}\"$0"),
				("pagetype=\"B5\"\tpagetype", "pagetype=\"${1:B5}\"$0"),
				("pagetype=\"custom\"\tpagetype", "pagetype=\"${1:custom}\"$0"),
				("pageheight\t@pageheight", "pageheight=\"$1\"$0"),
				("pagewidth\t@pagewidth", "pagewidth=\"$1\"$0"),
				("orientation\t@orientation", "orientation=\"$1\"$0"),
				("orientation=\"portrait\"\torientation", "orientation=\"${1:portrait}\"$0"),
				("orientation=\"landscape\"\torientation", "orientation=\"${1:landscape}\"$0"),
				("margintop\t@margintop", "margintop=\"$1\"$0"),
				("marginbottom\t@marginbottom", "marginbottom=\"$1\"$0"),
				("marginleft\t@marginleft", "marginleft=\"$1\"$0"),
				("marginright\t@marginright", "marginright=\"$1\"$0"),
				("unit\t@unit", "unit=\"$1\"$0"),
				("unit=\"in\"\tunit", "unit=\"${1:in}\"$0"),
				("unit=\"cm\"\tunit", "unit=\"${1:cm}\"$0"),
				("encryption\t@encryption", "encryption=\"$1\"$0"),
				("encryption=\"128-bit\"\tencryption", "encryption=\"${1:128-bit}\"$0"),
				("encryption=\"40-bit\"\tencryption", "encryption=\"${1:40-bit}\"$0"),
				("encryption=\"none\"\tencryption", "encryption=\"${1:none}\"$0"),
				("ownerpassword\t@ownerpassword", "ownerpassword=\"$1\"$0"),
				("userpassword\t@userpassword", "userpassword=\"$1\"$0"),
				("permissions\t@permissions", "permissions=\"$1\"$0"),
				("permissions=\"AllowPrinting,AllowCopy,AllowScreenReaders\"\tpermissions", "permissions=\"${1:AllowPrinting,AllowCopy,AllowScreenReaders}\"$0"),
				("permissions=\"AllowPrinting\"\tpermissions", "permissions=\"${1:AllowPrinting}\"$0"),
				("permissions=\"AllowModifyContents\"\tpermissions", "permissions=\"${1:AllowModifyContents}\"$0"),
				("permissions=\"AllowCopy\"\tpermissions", "permissions=\"${1:AllowCopy}\"$0"),
				("permissions=\"AllowModifyAnnotations\"\tpermissions", "permissions=\"${1:AllowModifyAnnotations}\"$0"),
				("permissions=\"AllowFillIn\"\tpermissions", "permissions=\"${1:AllowFillIn}\"$0"),
				("permissions=\"AllowScreenReaders\"\tpermissions", "permissions=\"${1:AllowScreenReaders}\"$0"),
				("permissions=\"AllowAssembly\"\tpermissions", "permissions=\"${1:AllowAssembly}\"$0"),
				("permissions=\"AllowDegradedPrinting\"\tpermissions", "permissions=\"${1:AllowDegradedPrinting}\"$0"),
				("permissions=\"AllowPrinting,AllowModifyContents,AllowCopy,AllowModifyAnnotations,AllowFillIn,AllowScreenReaders,AllowAssembly,AllowDegradedPrinting\"\tpermissions", "permissions=\"${1:AllowPrinting,AllowModifyContents,AllowCopy,AllowModifyAnnotations,AllowFillIn,AllowScreenReaders,AllowAssembly,AllowDegradedPrinting}\"$0"),
				("fontembed\t@fontembed", "fontembed=\"$1\"$0"),
				("fontembed=\"true\"\tfontembed", "fontembed=\"${1:true}\"$0"),
				("fontembed=\"false\"\tfontembed", "fontembed=\"${1:false}\"$0"),
				("backgroundvisible\t@backgroundvisible", "backgroundvisible=\"$1\"$0"),
				("backgroundvisible=\"true\"\tbackgroundvisible", "backgroundvisible=\"${1:true}\"$0"),
				("backgroundvisible=\"false\"\tbackgroundvisible", "backgroundvisible=\"${1:false}\"$0"),
				("scale\t@scale", "scale=\"$1\"$0"),
				("authpassword\t@authpassword", "authpassword=\"$1\"$0"),
				("authuser\t@authuser", "authuser=\"$1\"$0"),
				("bookmark\t@bookmark", "bookmark=\"$1\"$0"),
				("bookmark=\"true\"\tbookmark", "bookmark=\"${1:true}\"$0"),
				("bookmark=\"false\"\tbookmark", "bookmark=\"${1:false}\"$0"),
				("localurl\t@localurl", "localurl=\"$1\"$0"),
				("localurl=\"true\"\tlocalurl", "localurl=\"${1:true}\"$0"),
				("localurl=\"false\"\tlocalurl", "localurl=\"${1:false}\"$0"),
				("mimetype\t@mimetype", "mimetype=\"$1\"$0"),
				("mimetype=\"text/html\"\tmimetype", "mimetype=\"${1:text/html}\"$0"),
				("mimetype=\"text/plain\"\tmimetype", "mimetype=\"${1:text/plain}\"$0"),
				("mimetype=\"application/xml\"\tmimetype", "mimetype=\"${1:application/xml}\"$0"),
				("mimetype=\"image/bmp\"\tmimetype", "mimetype=\"${1:image/bmp}\"$0"),
				("mimetype=\"image/jpeg\"\tmimetype", "mimetype=\"${1:image/jpeg}\"$0"),
				("mimetype=\"image/png\"\tmimetype", "mimetype=\"${1:image/png}\"$0"),
				("mimetype=\"image/gif\"\tmimetype", "mimetype=\"${1:image/gif}\"$0"),
				("proxypassword\t@proxypassword", "proxypassword=\"$1\"$0"),
				("proxyuser\t@proxyuser", "proxyuser=\"$1\"$0"),
				("saveasname\t@saveasname", "saveasname=\"$1\"$0"),
				("src\t@src", "src=\"$1\"$0"),
				("srcfile\t@srcfile", "srcfile=\"$1\"$0"),
				("useragent\t@useragent", "useragent=\"$1\"$0"),
				("proxyhost\t@proxyhost", "proxyhost=\"$1\"$0"),
				("proxyport\t@proxyport", "proxyport=\"$1\"$0")
			],
			'attributes': [
				"saveasname",
				"orientation",
				"proxyport",
				"overwrite",
				"proxyhost",
				"backgroundvisible",
				"marginright",
				"src",
				"proxyuser",
				"authuser",
				"marginbottom",
				"margintop",
				"pagewidth",
				"ownerpassword",
				"authpassword",
				"srcfile",
				"useragent",
				"unit",
				"name",
				"scale",
				"pageheight",
				"permissions",
				"proxypassword",
				"filename",
				"localurl",
				"encryption",
				"bookmark",
				"userpassword",
				"format",
				"fontembed",
				"marginleft",
				"pagetype",
				"mimetype"
			]
		}
		self.completions['cfdocumentitem'] = {
			'completions': [
				("type\t@type", "type=\"$1\"$0"),
				("type=\"pagebreak\"\ttype", "type=\"${1:pagebreak}\"$0"),
				("type=\"header\"\ttype", "type=\"${1:header}\"$0"),
				("type=\"footer\"\ttype", "type=\"${1:footer}\"$0")
			],
			'attributes': [
				"type"
			]
		}
		self.completions['cfdump'] = {
			'completions': [
				("var\t@var", "var=\"$1\"$0"),
				("expand\t@expand", "expand=\"$1\"$0"),
				("expand=\"true\"\texpand", "expand=\"${1:true}\"$0"),
				("expand=\"false\"\texpand", "expand=\"${1:false}\"$0"),
				("format\t@format", "format=\"$1\"$0"),
				("format=\"html\"\tformat", "format=\"${1:html}\"$0"),
				("format=\"text\"\tformat", "format=\"${1:text}\"$0"),
				("hide\t@hide", "hide=\"$1\"$0"),
				("keys\t@keys", "keys=\"$1\"$0"),
				("label\t@label", "label=\"$1\"$0"),
				("metainfo\t@metainfo", "metainfo=\"$1\"$0"),
				("metainfo=\"true\"\tmetainfo", "metainfo=\"${1:true}\"$0"),
				("metainfo=\"false\"\tmetainfo", "metainfo=\"${1:false}\"$0"),
				("output\t@output", "output=\"$1\"$0"),
				("output=\"browser\"\toutput", "output=\"${1:browser}\"$0"),
				("output=\"console\"\toutput", "output=\"${1:console}\"$0"),
				("output=\"filename\"\toutput", "output=\"${1:filename}\"$0"),
				("show\t@show", "show=\"$1\"$0"),
				("showUDfs\t@showUDfs", "showUDfs=\"$1\"$0"),
				("showUDfs=\"true\"\tshowUDfs", "showUDfs=\"${1:true}\"$0"),
				("showUDfs=\"false\"\tshowUDfs", "showUDfs=\"${1:false}\"$0"),
				("top\t@top", "top=\"$1\"$0")
			],
			'attributes': [
				"showUDfs",
				"var",
				"hide",
				"format",
				"keys",
				"label",
				"top",
				"expand",
				"show",
				"output",
				"metainfo"
			]
		}
		self.completions['cffile'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"append\"\taction", "action=\"${1:append}\"$0"),
				("action=\"copy\"\taction", "action=\"${1:copy}\"$0"),
				("action=\"delete\"\taction", "action=\"${1:delete}\"$0"),
				("action=\"move\"\taction", "action=\"${1:move}\"$0"),
				("action=\"read\"\taction", "action=\"${1:read}\"$0"),
				("action=\"readbinary\"\taction", "action=\"${1:readbinary}\"$0"),
				("action=\"rename\"\taction", "action=\"${1:rename}\"$0"),
				("action=\"upload\"\taction", "action=\"${1:upload}\"$0"),
				("action=\"write\"\taction", "action=\"${1:write}\"$0"),
				("file\t@file", "file=\"$1\"$0"),
				("mode\t@mode", "mode=\"$1\"$0"),
				("output\t@output", "output=\"$1\"$0"),
				("addnewline\t@addnewline", "addnewline=\"$1\"$0"),
				("addnewline=\"true\"\taddnewline", "addnewline=\"${1:true}\"$0"),
				("addnewline=\"false\"\taddnewline", "addnewline=\"${1:false}\"$0"),
				("attributes\t@attributes", "attributes=\"$1\"$0"),
				("attributes=\"readonly\"\tattributes", "attributes=\"${1:readonly}\"$0"),
				("attributes=\"hidden\"\tattributes", "attributes=\"${1:hidden}\"$0"),
				("attributes=\"normal\"\tattributes", "attributes=\"${1:normal}\"$0"),
				("attributes=\"system\"\tattributes", "attributes=\"${1:system}\"$0"),
				("attributes=\"temporary\"\tattributes", "attributes=\"${1:temporary}\"$0"),
				("charset\t@charset", "charset=\"$1\"$0"),
				("charset=\"utf-8\"\tcharset", "charset=\"${1:utf-8}\"$0"),
				("charset=\"iso-8859-1\"\tcharset", "charset=\"${1:iso-8859-1}\"$0"),
				("charset=\"windows-1252\"\tcharset", "charset=\"${1:windows-1252}\"$0"),
				("charset=\"us-ascii\"\tcharset", "charset=\"${1:us-ascii}\"$0"),
				("charset=\"shift_jis\"\tcharset", "charset=\"${1:shift_jis}\"$0"),
				("charset=\"iso-2022-jp\"\tcharset", "charset=\"${1:iso-2022-jp}\"$0"),
				("charset=\"euc-jp\"\tcharset", "charset=\"${1:euc-jp}\"$0"),
				("charset=\"euc-kr\"\tcharset", "charset=\"${1:euc-kr}\"$0"),
				("charset=\"big5\"\tcharset", "charset=\"${1:big5}\"$0"),
				("charset=\"euc-cn\"\tcharset", "charset=\"${1:euc-cn}\"$0"),
				("charset=\"utf-16\"\tcharset", "charset=\"${1:utf-16}\"$0"),
				("source\t@source", "source=\"$1\"$0"),
				("destination\t@destination", "destination=\"$1\"$0"),
				("variable\t@variable", "variable=\"$1\"$0"),
				("filefield\t@filefield", "filefield=\"$1\"$0"),
				("nameconflict\t@nameconflict", "nameconflict=\"$1\"$0"),
				("nameconflict=\"error\"\tnameconflict", "nameconflict=\"${1:error}\"$0"),
				("nameconflict=\"skip\"\tnameconflict", "nameconflict=\"${1:skip}\"$0"),
				("nameconflict=\"overwrite\"\tnameconflict", "nameconflict=\"${1:overwrite}\"$0"),
				("nameconflict=\"makeunique\"\tnameconflict", "nameconflict=\"${1:makeunique}\"$0"),
				("accept\t@accept", "accept=\"$1\"$0"),
				("result\t@result", "result=\"$1\"$0"),
				("fixnewline\t@fixnewline", "fixnewline=\"$1\"$0"),
				("fixnewline=\"true\"\tfixnewline", "fixnewline=\"${1:true}\"$0"),
				("fixnewline=\"false\"\tfixnewline", "fixnewline=\"${1:false}\"$0")
			],
			'attributes': [
				"attributes",
				"variable",
				"destination",
				"addnewline",
				"source",
				"result",
				"fixnewline",
				"charset",
				"file",
				"accept",
				"mode",
				"output",
				"action",
				"filefield",
				"nameconflict"
			]
		}
		self.completions['cfgrid'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("bind\t@bind", "bind=\"$1\"$0"),
				("pagesize\t@pagesize", "pagesize=\"$1\"$0"),
				("striperowcolor\t@striperowcolor", "striperowcolor=\"$1\"$0"),
				("preservepageonsort\t@preservepageonsort", "preservepageonsort=\"$1\"$0"),
				("preservepageonsort=\"true\"\tpreservepageonsort", "preservepageonsort=\"${1:true}\"$0"),
				("preservepageonsort=\"false\"\tpreservepageonsort", "preservepageonsort=\"${1:false}\"$0"),
				("striperows\t@striperows", "striperows=\"$1\"$0"),
				("striperows=\"true\"\tstriperows", "striperows=\"${1:true}\"$0"),
				("striperows=\"false\"\tstriperows", "striperows=\"${1:false}\"$0"),
				("format\t@format", "format=\"$1\"$0"),
				("format=\"applet\"\tformat", "format=\"${1:applet}\"$0"),
				("format=\"flash\"\tformat", "format=\"${1:flash}\"$0"),
				("format=\"xml\"\tformat", "format=\"${1:xml}\"$0"),
				("format=\"html\"\tformat", "format=\"${1:html}\"$0"),
				("height\t@height", "height=\"$1\"$0"),
				("width\t@width", "width=\"$1\"$0"),
				("autowidth\t@autowidth", "autowidth=\"$1\"$0"),
				("autowidth=\"true\"\tautowidth", "autowidth=\"${1:true}\"$0"),
				("autowidth=\"false\"\tautowidth", "autowidth=\"${1:false}\"$0"),
				("vspace\t@vspace", "vspace=\"$1\"$0"),
				("hspace\t@hspace", "hspace=\"$1\"$0"),
				("align\t@align", "align=\"$1\"$0"),
				("align=\"top\"\talign", "align=\"${1:top}\"$0"),
				("align=\"left\"\talign", "align=\"${1:left}\"$0"),
				("align=\"bottom\"\talign", "align=\"${1:bottom}\"$0"),
				("align=\"baseline\"\talign", "align=\"${1:baseline}\"$0"),
				("align=\"texttop\"\talign", "align=\"${1:texttop}\"$0"),
				("align=\"absbottom\"\talign", "align=\"${1:absbottom}\"$0"),
				("align=\"middle\"\talign", "align=\"${1:middle}\"$0"),
				("align=\"absmiddle\"\talign", "align=\"${1:absmiddle}\"$0"),
				("align=\"right\"\talign", "align=\"${1:right}\"$0"),
				("query\t@query", "query=\"$1\"$0"),
				("insert\t@insert", "insert=\"$1\"$0"),
				("insert=\"true\"\tinsert", "insert=\"${1:true}\"$0"),
				("insert=\"false\"\tinsert", "insert=\"${1:false}\"$0"),
				("delete\t@delete", "delete=\"$1\"$0"),
				("delete=\"true\"\tdelete", "delete=\"${1:true}\"$0"),
				("delete=\"false\"\tdelete", "delete=\"${1:false}\"$0"),
				("sort\t@sort", "sort=\"$1\"$0"),
				("sort=\"true\"\tsort", "sort=\"${1:true}\"$0"),
				("sort=\"false\"\tsort", "sort=\"${1:false}\"$0"),
				("font\t@font", "font=\"$1\"$0"),
				("font=\"arial\"\tfont", "font=\"${1:arial}\"$0"),
				("font=\"times\"\tfont", "font=\"${1:times}\"$0"),
				("font=\"courier\"\tfont", "font=\"${1:courier}\"$0"),
				("font=\"arialunicodeMS\"\tfont", "font=\"${1:arialunicodeMS}\"$0"),
				("fontsize\t@fontsize", "fontsize=\"$1\"$0"),
				("italic\t@italic", "italic=\"$1\"$0"),
				("italic=\"true\"\titalic", "italic=\"${1:true}\"$0"),
				("italic=\"false\"\titalic", "italic=\"${1:false}\"$0"),
				("bold\t@bold", "bold=\"$1\"$0"),
				("bold=\"true\"\tbold", "bold=\"${1:true}\"$0"),
				("bold=\"false\"\tbold", "bold=\"${1:false}\"$0"),
				("textcolor\t@textcolor", "textcolor=\"$1\"$0"),
				("textcolor=\"black\"\ttextcolor", "textcolor=\"${1:black}\"$0"),
				("textcolor=\"red\"\ttextcolor", "textcolor=\"${1:red}\"$0"),
				("textcolor=\"blue\"\ttextcolor", "textcolor=\"${1:blue}\"$0"),
				("textcolor=\"magenta\"\ttextcolor", "textcolor=\"${1:magenta}\"$0"),
				("textcolor=\"cyan\"\ttextcolor", "textcolor=\"${1:cyan}\"$0"),
				("textcolor=\"orange\"\ttextcolor", "textcolor=\"${1:orange}\"$0"),
				("textcolor=\"darkgray\"\ttextcolor", "textcolor=\"${1:darkgray}\"$0"),
				("textcolor=\"pink\"\ttextcolor", "textcolor=\"${1:pink}\"$0"),
				("textcolor=\"white\"\ttextcolor", "textcolor=\"${1:white}\"$0"),
				("textcolor=\"lightgray\"\ttextcolor", "textcolor=\"${1:lightgray}\"$0"),
				("textcolor=\"yellow\"\ttextcolor", "textcolor=\"${1:yellow}\"$0"),
				("href\t@href", "href=\"$1\"$0"),
				("hrefkey\t@hrefkey", "hrefkey=\"$1\"$0"),
				("target\t@target", "target=\"$1\"$0"),
				("appendkey\t@appendkey", "appendkey=\"$1\"$0"),
				("appendkey=\"true\"\tappendkey", "appendkey=\"${1:true}\"$0"),
				("appendkey=\"false\"\tappendkey", "appendkey=\"${1:false}\"$0"),
				("highlighthref\t@highlighthref", "highlighthref=\"$1\"$0"),
				("highlighthref=\"true\"\thighlighthref", "highlighthref=\"${1:true}\"$0"),
				("highlighthref=\"false\"\thighlighthref", "highlighthref=\"${1:false}\"$0"),
				("onvalidate\t@onvalidate", "onvalidate=\"$1\"$0"),
				("onerror\t@onerror", "onerror=\"$1\"$0"),
				("griddataalign\t@griddataalign", "griddataalign=\"$1\"$0"),
				("griddataalign=\"left\"\tgriddataalign", "griddataalign=\"${1:left}\"$0"),
				("griddataalign=\"center\"\tgriddataalign", "griddataalign=\"${1:center}\"$0"),
				("griddataalign=\"right\"\tgriddataalign", "griddataalign=\"${1:right}\"$0"),
				("gridlines\t@gridlines", "gridlines=\"$1\"$0"),
				("gridlines=\"true\"\tgridlines", "gridlines=\"${1:true}\"$0"),
				("gridlines=\"false\"\tgridlines", "gridlines=\"${1:false}\"$0"),
				("rowheight\t@rowheight", "rowheight=\"$1\"$0"),
				("rowheaders\t@rowheaders", "rowheaders=\"$1\"$0"),
				("rowheaders=\"true\"\trowheaders", "rowheaders=\"${1:true}\"$0"),
				("rowheaders=\"false\"\trowheaders", "rowheaders=\"${1:false}\"$0"),
				("rowheaderalign\t@rowheaderalign", "rowheaderalign=\"$1\"$0"),
				("rowheaderalign=\"left\"\trowheaderalign", "rowheaderalign=\"${1:left}\"$0"),
				("rowheaderalign=\"center\"\trowheaderalign", "rowheaderalign=\"${1:center}\"$0"),
				("rowheaderalign=\"right\"\trowheaderalign", "rowheaderalign=\"${1:right}\"$0"),
				("rowheaderfont\t@rowheaderfont", "rowheaderfont=\"$1\"$0"),
				("rowheaderfontsize\t@rowheaderfontsize", "rowheaderfontsize=\"$1\"$0"),
				("rowheaderitalic\t@rowheaderitalic", "rowheaderitalic=\"$1\"$0"),
				("rowheaderitalic=\"true\"\trowheaderitalic", "rowheaderitalic=\"${1:true}\"$0"),
				("rowheaderitalic=\"false\"\trowheaderitalic", "rowheaderitalic=\"${1:false}\"$0"),
				("rowheaderbold\t@rowheaderbold", "rowheaderbold=\"$1\"$0"),
				("rowheaderbold=\"true\"\trowheaderbold", "rowheaderbold=\"${1:true}\"$0"),
				("rowheaderbold=\"false\"\trowheaderbold", "rowheaderbold=\"${1:false}\"$0"),
				("rowheadertextcolor\t@rowheadertextcolor", "rowheadertextcolor=\"$1\"$0"),
				("rowheadertextcolor=\"black\"\trowheadertextcolor", "rowheadertextcolor=\"${1:black}\"$0"),
				("rowheadertextcolor=\"red\"\trowheadertextcolor", "rowheadertextcolor=\"${1:red}\"$0"),
				("rowheadertextcolor=\"blue\"\trowheadertextcolor", "rowheadertextcolor=\"${1:blue}\"$0"),
				("rowheadertextcolor=\"magenta\"\trowheadertextcolor", "rowheadertextcolor=\"${1:magenta}\"$0"),
				("rowheadertextcolor=\"cyan\"\trowheadertextcolor", "rowheadertextcolor=\"${1:cyan}\"$0"),
				("rowheadertextcolor=\"orange\"\trowheadertextcolor", "rowheadertextcolor=\"${1:orange}\"$0"),
				("rowheadertextcolor=\"darkgray\"\trowheadertextcolor", "rowheadertextcolor=\"${1:darkgray}\"$0"),
				("rowheadertextcolor=\"pink\"\trowheadertextcolor", "rowheadertextcolor=\"${1:pink}\"$0"),
				("rowheadertextcolor=\"white\"\trowheadertextcolor", "rowheadertextcolor=\"${1:white}\"$0"),
				("rowheadertextcolor=\"lightgray\"\trowheadertextcolor", "rowheadertextcolor=\"${1:lightgray}\"$0"),
				("rowheadertextcolor=\"yellow\"\trowheadertextcolor", "rowheadertextcolor=\"${1:yellow}\"$0"),
				("colheaders\t@colheaders", "colheaders=\"$1\"$0"),
				("colheaders=\"true\"\tcolheaders", "colheaders=\"${1:true}\"$0"),
				("colheaders=\"false\"\tcolheaders", "colheaders=\"${1:false}\"$0"),
				("colheaderalign\t@colheaderalign", "colheaderalign=\"$1\"$0"),
				("colheaderalign=\"left\"\tcolheaderalign", "colheaderalign=\"${1:left}\"$0"),
				("colheaderalign=\"center\"\tcolheaderalign", "colheaderalign=\"${1:center}\"$0"),
				("colheaderalign=\"right\"\tcolheaderalign", "colheaderalign=\"${1:right}\"$0"),
				("colheaderfont\t@colheaderfont", "colheaderfont=\"$1\"$0"),
				("colheaderfontsize\t@colheaderfontsize", "colheaderfontsize=\"$1\"$0"),
				("colheaderitalic\t@colheaderitalic", "colheaderitalic=\"$1\"$0"),
				("colheaderitalic=\"true\"\tcolheaderitalic", "colheaderitalic=\"${1:true}\"$0"),
				("colheaderitalic=\"false\"\tcolheaderitalic", "colheaderitalic=\"${1:false}\"$0"),
				("colheaderbold\t@colheaderbold", "colheaderbold=\"$1\"$0"),
				("colheaderbold=\"true\"\tcolheaderbold", "colheaderbold=\"${1:true}\"$0"),
				("colheaderbold=\"false\"\tcolheaderbold", "colheaderbold=\"${1:false}\"$0"),
				("colheadertextcolor\t@colheadertextcolor", "colheadertextcolor=\"$1\"$0"),
				("colheadertextcolor=\"black\"\tcolheadertextcolor", "colheadertextcolor=\"${1:black}\"$0"),
				("colheadertextcolor=\"red\"\tcolheadertextcolor", "colheadertextcolor=\"${1:red}\"$0"),
				("colheadertextcolor=\"blue\"\tcolheadertextcolor", "colheadertextcolor=\"${1:blue}\"$0"),
				("colheadertextcolor=\"magenta\"\tcolheadertextcolor", "colheadertextcolor=\"${1:magenta}\"$0"),
				("colheadertextcolor=\"cyan\"\tcolheadertextcolor", "colheadertextcolor=\"${1:cyan}\"$0"),
				("colheadertextcolor=\"orange\"\tcolheadertextcolor", "colheadertextcolor=\"${1:orange}\"$0"),
				("colheadertextcolor=\"darkgray\"\tcolheadertextcolor", "colheadertextcolor=\"${1:darkgray}\"$0"),
				("colheadertextcolor=\"pink\"\tcolheadertextcolor", "colheadertextcolor=\"${1:pink}\"$0"),
				("colheadertextcolor=\"white\"\tcolheadertextcolor", "colheadertextcolor=\"${1:white}\"$0"),
				("colheadertextcolor=\"lightgray\"\tcolheadertextcolor", "colheadertextcolor=\"${1:lightgray}\"$0"),
				("colheadertextcolor=\"yellow\"\tcolheadertextcolor", "colheadertextcolor=\"${1:yellow}\"$0"),
				("bgcolor\t@bgcolor", "bgcolor=\"$1\"$0"),
				("bgcolor=\"black\"\tbgcolor", "bgcolor=\"${1:black}\"$0"),
				("bgcolor=\"red\"\tbgcolor", "bgcolor=\"${1:red}\"$0"),
				("bgcolor=\"blue\"\tbgcolor", "bgcolor=\"${1:blue}\"$0"),
				("bgcolor=\"magenta\"\tbgcolor", "bgcolor=\"${1:magenta}\"$0"),
				("bgcolor=\"cyan\"\tbgcolor", "bgcolor=\"${1:cyan}\"$0"),
				("bgcolor=\"orange\"\tbgcolor", "bgcolor=\"${1:orange}\"$0"),
				("bgcolor=\"darkgray\"\tbgcolor", "bgcolor=\"${1:darkgray}\"$0"),
				("bgcolor=\"pink\"\tbgcolor", "bgcolor=\"${1:pink}\"$0"),
				("bgcolor=\"white\"\tbgcolor", "bgcolor=\"${1:white}\"$0"),
				("bgcolor=\"lightgray\"\tbgcolor", "bgcolor=\"${1:lightgray}\"$0"),
				("bgcolor=\"yellow\"\tbgcolor", "bgcolor=\"${1:yellow}\"$0"),
				("selectcolor\t@selectcolor", "selectcolor=\"$1\"$0"),
				("selectcolor=\"black\"\tselectcolor", "selectcolor=\"${1:black}\"$0"),
				("selectcolor=\"red\"\tselectcolor", "selectcolor=\"${1:red}\"$0"),
				("selectcolor=\"blue\"\tselectcolor", "selectcolor=\"${1:blue}\"$0"),
				("selectcolor=\"magenta\"\tselectcolor", "selectcolor=\"${1:magenta}\"$0"),
				("selectcolor=\"cyan\"\tselectcolor", "selectcolor=\"${1:cyan}\"$0"),
				("selectcolor=\"orange\"\tselectcolor", "selectcolor=\"${1:orange}\"$0"),
				("selectcolor=\"darkgray\"\tselectcolor", "selectcolor=\"${1:darkgray}\"$0"),
				("selectcolor=\"pink\"\tselectcolor", "selectcolor=\"${1:pink}\"$0"),
				("selectcolor=\"white\"\tselectcolor", "selectcolor=\"${1:white}\"$0"),
				("selectcolor=\"lightgray\"\tselectcolor", "selectcolor=\"${1:lightgray}\"$0"),
				("selectcolor=\"yellow\"\tselectcolor", "selectcolor=\"${1:yellow}\"$0"),
				("selectmode\t@selectmode", "selectmode=\"$1\"$0"),
				("selectmode=\"edit\"\tselectmode", "selectmode=\"${1:edit}\"$0"),
				("selectmode=\"single\"\tselectmode", "selectmode=\"${1:single}\"$0"),
				("selectmode=\"row\"\tselectmode", "selectmode=\"${1:row}\"$0"),
				("selectmode=\"column\"\tselectmode", "selectmode=\"${1:column}\"$0"),
				("selectmode=\"browse\"\tselectmode", "selectmode=\"${1:browse}\"$0"),
				("maxrows\t@maxrows", "maxrows=\"$1\"$0"),
				("notsupported\t@notsupported", "notsupported=\"$1\"$0"),
				("picturebar\t@picturebar", "picturebar=\"$1\"$0"),
				("picturebar=\"true\"\tpicturebar", "picturebar=\"${1:true}\"$0"),
				("picturebar=\"false\"\tpicturebar", "picturebar=\"${1:false}\"$0"),
				("insertbutton\t@insertbutton", "insertbutton=\"$1\"$0"),
				("deletebutton\t@deletebutton", "deletebutton=\"$1\"$0"),
				("sortascendingbutton\t@sortascendingbutton", "sortascendingbutton=\"$1\"$0"),
				("sortdescendingbutton\t@sortdescendingbutton", "sortdescendingbutton=\"$1\"$0"),
				("style\t@style", "style=\"$1\"$0"),
				("enabled\t@enabled", "enabled=\"$1\"$0"),
				("enabled=\"true\"\tenabled", "enabled=\"${1:true}\"$0"),
				("enabled=\"false\"\tenabled", "enabled=\"${1:false}\"$0"),
				("visible\t@visible", "visible=\"$1\"$0"),
				("visible=\"true\"\tvisible", "visible=\"${1:true}\"$0"),
				("visible=\"false\"\tvisible", "visible=\"${1:false}\"$0"),
				("tooltip\t@tooltip", "tooltip=\"$1\"$0"),
				("onchange\t@onchange", "onchange=\"$1\"$0"),
				("bindonload\t@bindonload", "bindonload=\"$1\"$0"),
				("bindonload=\"true\"\tbindonload", "bindonload=\"${1:true}\"$0"),
				("bindonload=\"false\"\tbindonload", "bindonload=\"${1:false}\"$0"),
				("selectonload\t@selectonload", "selectonload=\"$1\"$0"),
				("selectonload=\"true\"\tselectonload", "selectonload=\"${1:true}\"$0"),
				("selectonload=\"false\"\tselectonload", "selectonload=\"${1:false}\"$0"),
				("onblur\t@onblur", "onblur=\"$1\"$0"),
				("onfocus\t@onfocus", "onfocus=\"$1\"$0")
			],
			'attributes': [
				"tooltip",
				"rowheaderalign",
				"colheaderfontsize",
				"autowidth",
				"href",
				"notsupported",
				"selectonload",
				"onerror",
				"colheaderfont",
				"gridlines",
				"insertbutton",
				"rowheadertextcolor",
				"hrefkey",
				"name",
				"bold",
				"insert",
				"rowheight",
				"colheaderbold",
				"bind",
				"fontsize",
				"sortdescendingbutton",
				"rowheaders",
				"enabled",
				"font",
				"align",
				"rowheaderfont",
				"striperowcolor",
				"selectmode",
				"colheaderitalic",
				"pagesize",
				"preservepageonsort",
				"height",
				"bindonload",
				"rowheaderitalic",
				"appendkey",
				"onvalidate",
				"maxrows",
				"rowheaderbold",
				"visible",
				"sort",
				"onchange",
				"delete",
				"target",
				"vspace",
				"onblur",
				"hspace",
				"striperows",
				"bgcolor",
				"picturebar",
				"colheadertextcolor",
				"colheaders",
				"onfocus",
				"griddataalign",
				"sortascendingbutton",
				"highlighthref",
				"width",
				"style",
				"textcolor",
				"query",
				"italic",
				"format",
				"rowheaderfontsize",
				"deletebutton",
				"colheaderalign",
				"selectcolor"
			]
		}
		self.completions['cfgridcolumn'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("header\t@header", "header=\"$1\"$0"),
				("width\t@width", "width=\"$1\"$0"),
				("font\t@font", "font=\"$1\"$0"),
				("font=\"arial\"\tfont", "font=\"${1:arial}\"$0"),
				("font=\"times\"\tfont", "font=\"${1:times}\"$0"),
				("font=\"courier\"\tfont", "font=\"${1:courier}\"$0"),
				("font=\"arialunicodeMS\"\tfont", "font=\"${1:arialunicodeMS}\"$0"),
				("fontsize\t@fontsize", "fontsize=\"$1\"$0"),
				("italic\t@italic", "italic=\"$1\"$0"),
				("italic=\"true\"\titalic", "italic=\"${1:true}\"$0"),
				("italic=\"false\"\titalic", "italic=\"${1:false}\"$0"),
				("bold\t@bold", "bold=\"$1\"$0"),
				("bold=\"true\"\tbold", "bold=\"${1:true}\"$0"),
				("bold=\"false\"\tbold", "bold=\"${1:false}\"$0"),
				("bgcolor\t@bgcolor", "bgcolor=\"$1\"$0"),
				("bgcolor=\"black\"\tbgcolor", "bgcolor=\"${1:black}\"$0"),
				("bgcolor=\"red\"\tbgcolor", "bgcolor=\"${1:red}\"$0"),
				("bgcolor=\"blue\"\tbgcolor", "bgcolor=\"${1:blue}\"$0"),
				("bgcolor=\"magenta\"\tbgcolor", "bgcolor=\"${1:magenta}\"$0"),
				("bgcolor=\"cyan\"\tbgcolor", "bgcolor=\"${1:cyan}\"$0"),
				("bgcolor=\"orange\"\tbgcolor", "bgcolor=\"${1:orange}\"$0"),
				("bgcolor=\"darkgray\"\tbgcolor", "bgcolor=\"${1:darkgray}\"$0"),
				("bgcolor=\"pink\"\tbgcolor", "bgcolor=\"${1:pink}\"$0"),
				("bgcolor=\"white\"\tbgcolor", "bgcolor=\"${1:white}\"$0"),
				("bgcolor=\"lightgray\"\tbgcolor", "bgcolor=\"${1:lightgray}\"$0"),
				("bgcolor=\"yellow\"\tbgcolor", "bgcolor=\"${1:yellow}\"$0"),
				("textcolor\t@textcolor", "textcolor=\"$1\"$0"),
				("textcolor=\"black\"\ttextcolor", "textcolor=\"${1:black}\"$0"),
				("textcolor=\"red\"\ttextcolor", "textcolor=\"${1:red}\"$0"),
				("textcolor=\"blue\"\ttextcolor", "textcolor=\"${1:blue}\"$0"),
				("textcolor=\"magenta\"\ttextcolor", "textcolor=\"${1:magenta}\"$0"),
				("textcolor=\"cyan\"\ttextcolor", "textcolor=\"${1:cyan}\"$0"),
				("textcolor=\"orange\"\ttextcolor", "textcolor=\"${1:orange}\"$0"),
				("textcolor=\"darkgray\"\ttextcolor", "textcolor=\"${1:darkgray}\"$0"),
				("textcolor=\"pink\"\ttextcolor", "textcolor=\"${1:pink}\"$0"),
				("textcolor=\"white\"\ttextcolor", "textcolor=\"${1:white}\"$0"),
				("textcolor=\"lightgray\"\ttextcolor", "textcolor=\"${1:lightgray}\"$0"),
				("textcolor=\"yellow\"\ttextcolor", "textcolor=\"${1:yellow}\"$0"),
				("href\t@href", "href=\"$1\"$0"),
				("hrefkey\t@hrefkey", "hrefkey=\"$1\"$0"),
				("target\t@target", "target=\"$1\"$0"),
				("select\t@select", "select=\"$1\"$0"),
				("select=\"true\"\tselect", "select=\"${1:true}\"$0"),
				("select=\"false\"\tselect", "select=\"${1:false}\"$0"),
				("display\t@display", "display=\"$1\"$0"),
				("display=\"true\"\tdisplay", "display=\"${1:true}\"$0"),
				("display=\"false\"\tdisplay", "display=\"${1:false}\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"string_noCase\"\ttype", "type=\"${1:string_noCase}\"$0"),
				("type=\"boolean\"\ttype", "type=\"${1:boolean}\"$0"),
				("type=\"numeric\"\ttype", "type=\"${1:numeric}\"$0"),
				("type=\"date\"\ttype", "type=\"${1:date}\"$0"),
				("type=\"combobox\"\ttype", "type=\"${1:combobox}\"$0"),
				("type=\"image\"\ttype", "type=\"${1:image}\"$0"),
				("headerfont\t@headerfont", "headerfont=\"$1\"$0"),
				("headerfontsize\t@headerfontsize", "headerfontsize=\"$1\"$0"),
				("headeritalic\t@headeritalic", "headeritalic=\"$1\"$0"),
				("headeritalic=\"true\"\theaderitalic", "headeritalic=\"${1:true}\"$0"),
				("headeritalic=\"false\"\theaderitalic", "headeritalic=\"${1:false}\"$0"),
				("headerbold\t@headerbold", "headerbold=\"$1\"$0"),
				("headerbold=\"true\"\theaderbold", "headerbold=\"${1:true}\"$0"),
				("headerbold=\"false\"\theaderbold", "headerbold=\"${1:false}\"$0"),
				("headertextcolor\t@headertextcolor", "headertextcolor=\"$1\"$0"),
				("headertextcolor=\"black\"\theadertextcolor", "headertextcolor=\"${1:black}\"$0"),
				("headertextcolor=\"red\"\theadertextcolor", "headertextcolor=\"${1:red}\"$0"),
				("headertextcolor=\"blue\"\theadertextcolor", "headertextcolor=\"${1:blue}\"$0"),
				("headertextcolor=\"magenta\"\theadertextcolor", "headertextcolor=\"${1:magenta}\"$0"),
				("headertextcolor=\"cyan\"\theadertextcolor", "headertextcolor=\"${1:cyan}\"$0"),
				("headertextcolor=\"orange\"\theadertextcolor", "headertextcolor=\"${1:orange}\"$0"),
				("headertextcolor=\"darkgray\"\theadertextcolor", "headertextcolor=\"${1:darkgray}\"$0"),
				("headertextcolor=\"pink\"\theadertextcolor", "headertextcolor=\"${1:pink}\"$0"),
				("headertextcolor=\"white\"\theadertextcolor", "headertextcolor=\"${1:white}\"$0"),
				("headertextcolor=\"lightgray\"\theadertextcolor", "headertextcolor=\"${1:lightgray}\"$0"),
				("headertextcolor=\"yellow\"\theadertextcolor", "headertextcolor=\"${1:yellow}\"$0"),
				("dataalign\t@dataalign", "dataalign=\"$1\"$0"),
				("dataalign=\"left\"\tdataalign", "dataalign=\"${1:left}\"$0"),
				("dataalign=\"right\"\tdataalign", "dataalign=\"${1:right}\"$0"),
				("dataalign=\"center\"\tdataalign", "dataalign=\"${1:center}\"$0"),
				("headeralign\t@headeralign", "headeralign=\"$1\"$0"),
				("headeralign=\"left\"\theaderalign", "headeralign=\"${1:left}\"$0"),
				("headeralign=\"right\"\theaderalign", "headeralign=\"${1:right}\"$0"),
				("headeralign=\"center\"\theaderalign", "headeralign=\"${1:center}\"$0"),
				("numberformat\t@numberformat", "numberformat=\"$1\"$0"),
				("values\t@values", "values=\"$1\"$0"),
				("valuesdisplay\t@valuesdisplay", "valuesdisplay=\"$1\"$0"),
				("valuesdelimiter\t@valuesdelimiter", "valuesdelimiter=\"$1\"$0"),
				("valuesdelimiter=\",\"\tvaluesdelimiter", "valuesdelimiter=\"${1:,}\"$0"),
				("valuesdelimiter=\";\"\tvaluesdelimiter", "valuesdelimiter=\"${1:;}\"$0"),
				("valuesdelimiter=\"|\"\tvaluesdelimiter", "valuesdelimiter=\"${1:|}\"$0"),
				("valuesdelimiter=\":\"\tvaluesdelimiter", "valuesdelimiter=\"${1::}\"$0"),
				("mask\t@mask", "mask=\"$1\"$0")
			],
			'attributes': [
				"numberformat",
				"valuesdelimiter",
				"headeralign",
				"href",
				"values",
				"target",
				"headerbold",
				"type",
				"bgcolor",
				"hrefkey",
				"name",
				"mask",
				"bold",
				"headeritalic",
				"headerfont",
				"dataalign",
				"display",
				"fontsize",
				"width",
				"textcolor",
				"italic",
				"font",
				"headerfontsize",
				"headertextcolor",
				"header",
				"select",
				"valuesdisplay"
			]
		}
		self.completions['cfgridrow'] = {
			'completions': [
				("data\t@data", "data=\"$1\"$0")
			],
			'attributes': [
				"data"
			]
		}
		self.completions['cfhttp'] = {
			'completions': [
				("url\t@url", "url=\"$1\"$0"),
				("port\t@port", "port=\"$1\"$0"),
				("method\t@method", "method=\"$1\"$0"),
				("method=\"get\"\tmethod", "method=\"${1:get}\"$0"),
				("method=\"post\"\tmethod", "method=\"${1:post}\"$0"),
				("method=\"put\"\tmethod", "method=\"${1:put}\"$0"),
				("method=\"delete\"\tmethod", "method=\"${1:delete}\"$0"),
				("method=\"head\"\tmethod", "method=\"${1:head}\"$0"),
				("method=\"trace\"\tmethod", "method=\"${1:trace}\"$0"),
				("method=\"options\"\tmethod", "method=\"${1:options}\"$0"),
				("proxyserver\t@proxyserver", "proxyserver=\"$1\"$0"),
				("proxyport\t@proxyport", "proxyport=\"$1\"$0"),
				("proxyuser\t@proxyuser", "proxyuser=\"$1\"$0"),
				("proxypassword\t@proxypassword", "proxypassword=\"$1\"$0"),
				("username\t@username", "username=\"$1\"$0"),
				("password\t@password", "password=\"$1\"$0"),
				("useragent\t@useragent", "useragent=\"$1\"$0"),
				("charset\t@charset", "charset=\"$1\"$0"),
				("charset=\"utf-8\"\tcharset", "charset=\"${1:utf-8}\"$0"),
				("charset=\"iso-8859-1\"\tcharset", "charset=\"${1:iso-8859-1}\"$0"),
				("charset=\"windows-1252\"\tcharset", "charset=\"${1:windows-1252}\"$0"),
				("charset=\"us-ascii\"\tcharset", "charset=\"${1:us-ascii}\"$0"),
				("charset=\"shift_jis\"\tcharset", "charset=\"${1:shift_jis}\"$0"),
				("charset=\"iso-2022-jp\"\tcharset", "charset=\"${1:iso-2022-jp}\"$0"),
				("charset=\"euc-jp\"\tcharset", "charset=\"${1:euc-jp}\"$0"),
				("charset=\"euc-kr\"\tcharset", "charset=\"${1:euc-kr}\"$0"),
				("charset=\"big5\"\tcharset", "charset=\"${1:big5}\"$0"),
				("charset=\"euc-cn\"\tcharset", "charset=\"${1:euc-cn}\"$0"),
				("charset=\"utf-16\"\tcharset", "charset=\"${1:utf-16}\"$0"),
				("resolveurl\t@resolveurl", "resolveurl=\"$1\"$0"),
				("resolveurl=\"true\"\tresolveurl", "resolveurl=\"${1:true}\"$0"),
				("resolveurl=\"false\"\tresolveurl", "resolveurl=\"${1:false}\"$0"),
				("throwonerror\t@throwonerror", "throwonerror=\"$1\"$0"),
				("throwonerror=\"true\"\tthrowonerror", "throwonerror=\"${1:true}\"$0"),
				("throwonerror=\"false\"\tthrowonerror", "throwonerror=\"${1:false}\"$0"),
				("redirect\t@redirect", "redirect=\"$1\"$0"),
				("redirect=\"true\"\tredirect", "redirect=\"${1:true}\"$0"),
				("redirect=\"false\"\tredirect", "redirect=\"${1:false}\"$0"),
				("timeout\t@timeout", "timeout=\"$1\"$0"),
				("getasbinary\t@getasbinary", "getasbinary=\"$1\"$0"),
				("getasbinary=\"auto\"\tgetasbinary", "getasbinary=\"${1:auto}\"$0"),
				("getasbinary=\"yes\"\tgetasbinary", "getasbinary=\"${1:yes}\"$0"),
				("getasbinary=\"no\"\tgetasbinary", "getasbinary=\"${1:no}\"$0"),
				("getasbinary=\"never\"\tgetasbinary", "getasbinary=\"${1:never}\"$0"),
				("result\t@result", "result=\"$1\"$0"),
				("delimiter\t@delimiter", "delimiter=\"$1\"$0"),
				("delimiter=\",\"\tdelimiter", "delimiter=\"${1:,}\"$0"),
				("delimiter=\";\"\tdelimiter", "delimiter=\"${1:;}\"$0"),
				("delimiter=\"|\"\tdelimiter", "delimiter=\"${1:|}\"$0"),
				("delimiter=\":\"\tdelimiter", "delimiter=\"${1::}\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("columns\t@columns", "columns=\"$1\"$0"),
				("firstrowasheaders\t@firstrowasheaders", "firstrowasheaders=\"$1\"$0"),
				("firstrowasheaders=\"true\"\tfirstrowasheaders", "firstrowasheaders=\"${1:true}\"$0"),
				("firstrowasheaders=\"false\"\tfirstrowasheaders", "firstrowasheaders=\"${1:false}\"$0"),
				("textqualifier\t@textqualifier", "textqualifier=\"$1\"$0"),
				("textqualifier=\"\"\ttextqualifier", "textqualifier=\"${1:}\"$0"),
				("textqualifier=\"'\"\ttextqualifier", "textqualifier=\"${1:'}\"$0"),
				("file\t@file", "file=\"$1\"$0"),
				("multipart\t@multipart", "multipart=\"$1\"$0"),
				("multipart=\"true\"\tmultipart", "multipart=\"${1:true}\"$0"),
				("multipart=\"false\"\tmultipart", "multipart=\"${1:false}\"$0"),
				("clientcertpassword\t@clientcertpassword", "clientcertpassword=\"$1\"$0"),
				("path\t@path", "path=\"$1\"$0"),
				("clientcert\t@clientcert", "clientcert=\"$1\"$0")
			],
			'attributes': [
				"proxyport",
				"multipart",
				"resolveurl",
				"proxyuser",
				"getasbinary",
				"port",
				"result",
				"clientcert",
				"throwonerror",
				"charset",
				"file",
				"clientcertpassword",
				"password",
				"url",
				"proxyserver",
				"columns",
				"useragent",
				"name",
				"textqualifier",
				"proxypassword",
				"redirect",
				"path",
				"firstrowasheaders",
				"username",
				"method",
				"delimiter",
				"timeout"
			]
		}

		del self.completions['cffinally']
		del self.completions['cfcontinue']
		del self.completions['cfimap']
		self.completions['cfimport'] = {
			'completions': [
				("taglib\t@taglib", "taglib=\"$1\"$0"),
				("prefix\t@prefix", "prefix=\"$1\"$0")
			],
			'attributes': [
				"prefix",
				"taglib"
			]
		}
		self.completions['cfinput'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("autosuggest\t@autosuggest", "autosuggest=\"$1\"$0"),
				("autosuggestbinddelay\t@autosuggestbinddelay", "autosuggestbinddelay=\"$1\"$0"),
				("autosuggestminlength\t@autosuggestminlength", "autosuggestminlength=\"$1\"$0"),
				("bindattribute\t@bindattribute", "bindattribute=\"$1\"$0"),
				("bindonload\t@bindonload", "bindonload=\"$1\"$0"),
				("bindonload=\"true\"\tbindonload", "bindonload=\"${1:true}\"$0"),
				("bindonload=\"false\"\tbindonload", "bindonload=\"${1:false}\"$0"),
				("id\t@id", "id=\"$1\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"button\"\ttype", "type=\"${1:button}\"$0"),
				("type=\"checkbox\"\ttype", "type=\"${1:checkbox}\"$0"),
				("type=\"file\"\ttype", "type=\"${1:file}\"$0"),
				("type=\"hidden\"\ttype", "type=\"${1:hidden}\"$0"),
				("type=\"image\"\ttype", "type=\"${1:image}\"$0"),
				("type=\"password\"\ttype", "type=\"${1:password}\"$0"),
				("type=\"radio\"\ttype", "type=\"${1:radio}\"$0"),
				("type=\"reset\"\ttype", "type=\"${1:reset}\"$0"),
				("type=\"submit\"\ttype", "type=\"${1:submit}\"$0"),
				("type=\"text\"\ttype", "type=\"${1:text}\"$0"),
				("type=\"datefield\"\ttype", "type=\"${1:datefield}\"$0"),
				("label\t@label", "label=\"$1\"$0"),
				("style\t@style", "style=\"$1\"$0"),
				("class\t@class", "class=\"$1\"$0"),
				("required\t@required", "required=\"$1\"$0"),
				("required=\"true\"\trequired", "required=\"${1:true}\"$0"),
				("required=\"false\"\trequired", "required=\"${1:false}\"$0"),
				("mask\t@mask", "mask=\"$1\"$0"),
				("validate\t@validate", "validate=\"$1\"$0"),
				("validate=\"date\"\tvalidate", "validate=\"${1:date}\"$0"),
				("validate=\"eurodate\"\tvalidate", "validate=\"${1:eurodate}\"$0"),
				("validate=\"time\"\tvalidate", "validate=\"${1:time}\"$0"),
				("validate=\"float\"\tvalidate", "validate=\"${1:float}\"$0"),
				("validate=\"integer\"\tvalidate", "validate=\"${1:integer}\"$0"),
				("validate=\"telephone\"\tvalidate", "validate=\"${1:telephone}\"$0"),
				("validate=\"zipcode\"\tvalidate", "validate=\"${1:zipcode}\"$0"),
				("validate=\"creditcard\"\tvalidate", "validate=\"${1:creditcard}\"$0"),
				("validate=\"social_security_number\"\tvalidate", "validate=\"${1:social_security_number}\"$0"),
				("validate=\"regular_expression\"\tvalidate", "validate=\"${1:regular_expression}\"$0"),
				("validateat\t@validateat", "validateat=\"$1\"$0"),
				("validateat=\"onSubmit\"\tvalidateat", "validateat=\"${1:onSubmit}\"$0"),
				("validateat=\"onServer\"\tvalidateat", "validateat=\"${1:onServer}\"$0"),
				("validateat=\"onBlur\"\tvalidateat", "validateat=\"${1:onBlur}\"$0"),
				("message\t@message", "message=\"$1\"$0"),
				("range\t@range", "range=\"$1\"$0"),
				("maxlength\t@maxlength", "maxlength=\"$1\"$0"),
				("pattern\t@pattern", "pattern=\"$1\"$0"),
				("onvalidate\t@onvalidate", "onvalidate=\"$1\"$0"),
				("onerror\t@onerror", "onerror=\"$1\"$0"),
				("size\t@size", "size=\"$1\"$0"),
				("value\t@value", "value=\"$1\"$0"),
				("bind\t@bind", "bind=\"$1\"$0"),
				("checked\t@checked", "checked=\"$1\"$0"),
				("checked=\"true\"\tchecked", "checked=\"${1:true}\"$0"),
				("checked=\"false\"\tchecked", "checked=\"${1:false}\"$0"),
				("disabled\t@disabled", "disabled=\"$1\"$0"),
				("disabled=\"true\"\tdisabled", "disabled=\"${1:true}\"$0"),
				("disabled=\"false\"\tdisabled", "disabled=\"${1:false}\"$0"),
				("src\t@src", "src=\"$1\"$0"),
				("onkeyup\t@onkeyup", "onkeyup=\"$1\"$0"),
				("onkeydown\t@onkeydown", "onkeydown=\"$1\"$0"),
				("onmouseup\t@onmouseup", "onmouseup=\"$1\"$0"),
				("onmousedown\t@onmousedown", "onmousedown=\"$1\"$0"),
				("onchange\t@onchange", "onchange=\"$1\"$0"),
				("onclick\t@onclick", "onclick=\"$1\"$0"),
				("daynames\t@daynames", "daynames=\"$1\"$0"),
				("daynames=\"S\"\tdaynames", "daynames=\"${1:S}\"$0"),
				("daynames=\"M\"\tdaynames", "daynames=\"${1:M}\"$0"),
				("daynames=\"T\"\tdaynames", "daynames=\"${1:T}\"$0"),
				("daynames=\"W\"\tdaynames", "daynames=\"${1:W}\"$0"),
				("daynames=\"Th\"\tdaynames", "daynames=\"${1:Th}\"$0"),
				("daynames=\"F\"\tdaynames", "daynames=\"${1:F}\"$0"),
				("daynames=\"Sa\"\tdaynames", "daynames=\"${1:Sa}\"$0"),
				("daynames=\"Sunday\"\tdaynames", "daynames=\"${1:Sunday}\"$0"),
				("daynames=\"Monday\"\tdaynames", "daynames=\"${1:Monday}\"$0"),
				("daynames=\"Tuesday\"\tdaynames", "daynames=\"${1:Tuesday}\"$0"),
				("daynames=\"Wednesday\"\tdaynames", "daynames=\"${1:Wednesday}\"$0"),
				("daynames=\"Thursday\"\tdaynames", "daynames=\"${1:Thursday}\"$0"),
				("daynames=\"Friday\"\tdaynames", "daynames=\"${1:Friday}\"$0"),
				("daynames=\"Saturday\"\tdaynames", "daynames=\"${1:Saturday}\"$0"),
				("daynames=\"Sun\"\tdaynames", "daynames=\"${1:Sun}\"$0"),
				("daynames=\"Mon\"\tdaynames", "daynames=\"${1:Mon}\"$0"),
				("daynames=\"Tue\"\tdaynames", "daynames=\"${1:Tue}\"$0"),
				("daynames=\"Wed\"\tdaynames", "daynames=\"${1:Wed}\"$0"),
				("daynames=\"Thu\"\tdaynames", "daynames=\"${1:Thu}\"$0"),
				("daynames=\"Fri\"\tdaynames", "daynames=\"${1:Fri}\"$0"),
				("daynames=\"Sat\"\tdaynames", "daynames=\"${1:Sat}\"$0"),
				("firstdayofweek\t@firstdayofweek", "firstdayofweek=\"$1\"$0"),
				("monthnames\t@monthnames", "monthnames=\"$1\"$0"),
				("monthnames=\"January\"\tmonthnames", "monthnames=\"${1:January}\"$0"),
				("monthnames=\"February\"\tmonthnames", "monthnames=\"${1:February}\"$0"),
				("monthnames=\"March\"\tmonthnames", "monthnames=\"${1:March}\"$0"),
				("monthnames=\"April\"\tmonthnames", "monthnames=\"${1:April}\"$0"),
				("monthnames=\"May\"\tmonthnames", "monthnames=\"${1:May}\"$0"),
				("monthnames=\"June\"\tmonthnames", "monthnames=\"${1:June}\"$0"),
				("monthnames=\"July\"\tmonthnames", "monthnames=\"${1:July}\"$0"),
				("monthnames=\"August\"\tmonthnames", "monthnames=\"${1:August}\"$0"),
				("monthnames=\"September\"\tmonthnames", "monthnames=\"${1:September}\"$0"),
				("monthnames=\"October\"\tmonthnames", "monthnames=\"${1:October}\"$0"),
				("monthnames=\"November\"\tmonthnames", "monthnames=\"${1:November}\"$0"),
				("monthnames=\"December\"\tmonthnames", "monthnames=\"${1:December}\"$0"),
				("monthnames=\"Jan\"\tmonthnames", "monthnames=\"${1:Jan}\"$0"),
				("monthnames=\"Feb\"\tmonthnames", "monthnames=\"${1:Feb}\"$0"),
				("monthnames=\"Mar\"\tmonthnames", "monthnames=\"${1:Mar}\"$0"),
				("monthnames=\"Apr\"\tmonthnames", "monthnames=\"${1:Apr}\"$0"),
				("monthnames=\"May\"\tmonthnames", "monthnames=\"${1:May}\"$0"),
				("monthnames=\"Jun\"\tmonthnames", "monthnames=\"${1:Jun}\"$0"),
				("monthnames=\"Jul\"\tmonthnames", "monthnames=\"${1:Jul}\"$0"),
				("monthnames=\"Aug\"\tmonthnames", "monthnames=\"${1:Aug}\"$0"),
				("monthnames=\"Sep\"\tmonthnames", "monthnames=\"${1:Sep}\"$0"),
				("monthnames=\"Oct\"\tmonthnames", "monthnames=\"${1:Oct}\"$0"),
				("monthnames=\"Nov\"\tmonthnames", "monthnames=\"${1:Nov}\"$0"),
				("monthnames=\"Dec\"\tmonthnames", "monthnames=\"${1:Dec}\"$0"),
				("enabled\t@enabled", "enabled=\"$1\"$0"),
				("enabled=\"true\"\tenabled", "enabled=\"${1:true}\"$0"),
				("enabled=\"false\"\tenabled", "enabled=\"${1:false}\"$0"),
				("visible\t@visible", "visible=\"$1\"$0"),
				("visible=\"true\"\tvisible", "visible=\"${1:true}\"$0"),
				("visible=\"false\"\tvisible", "visible=\"${1:false}\"$0"),
				("tooltip\t@tooltip", "tooltip=\"$1\"$0"),
				("width\t@width", "width=\"$1\"$0"),
				("height\t@height", "height=\"$1\"$0"),
				("passthrough\t@passthrough", "passthrough=\"$1\"$0"),
				("delimiter\t@delimiter", "delimiter=\"$1\"$0"),
				("maxresultsdisplayed\t@maxresultsdisplayed", "maxresultsdisplayed=\"$1\"$0"),
				("onbinderror\t@onbinderror", "onbinderror=\"$1\"$0"),
				("showautosuggestloadingicon\t@showautosuggestloadingicon", "showautosuggestloadingicon=\"$1\"$0"),
				("showautosuggestloadingicon=\"true\"\tshowautosuggestloadingicon", "showautosuggestloadingicon=\"${1:true}\"$0"),
				("showautosuggestloadingicon=\"false\"\tshowautosuggestloadingicon", "showautosuggestloadingicon=\"${1:false}\"$0"),
				("sourcefortooltip\t@sourcefortooltip", "sourcefortooltip=\"$1\"$0"),
				("typeahead\t@typeahead", "typeahead=\"$1\"$0"),
				("typeahead=\"true\"\ttypeahead", "typeahead=\"${1:true}\"$0"),
				("typeahead=\"false\"\ttypeahead", "typeahead=\"${1:false}\"$0")
			],
			'attributes': [
				"monthnames",
				"class",
				"tooltip",
				"validateat",
				"height",
				"autosuggestminlength",
				"bindonload",
				"disabled",
				"src",
				"onvalidate",
				"maxresultsdisplayed",
				"visible",
				"autosuggestbinddelay",
				"range",
				"onchange",
				"firstdayofweek",
				"showautosuggestloadingicon",
				"daynames",
				"onmousedown",
				"required",
				"onerror",
				"value",
				"id",
				"onbinderror",
				"bindattribute",
				"type",
				"sourcefortooltip",
				"onmouseup",
				"pattern",
				"onkeydown",
				"onkeyup",
				"name",
				"mask",
				"label",
				"typeahead",
				"bind",
				"validate",
				"checked",
				"width",
				"style",
				"maxlength",
				"onclick",
				"enabled",
				"message",
				"autosuggest",
				"passthrough",
				"size",
				"delimiter"
			]
		}
		self.completions['cflayout'] = {
			'completions': [
				("type\t@type", "type=\"$1\"$0"),
				("type=\"border\"\ttype", "type=\"${1:border}\"$0"),
				("type=\"hbox\"\ttype", "type=\"${1:hbox}\"$0"),
				("type=\"tab\"\ttype", "type=\"${1:tab}\"$0"),
				("type=\"vbox\"\ttype", "type=\"${1:vbox}\"$0"),
				("align\t@align", "align=\"$1\"$0"),
				("align=\"center\"\talign", "align=\"${1:center}\"$0"),
				("align=\"justify\"\talign", "align=\"${1:justify}\"$0"),
				("align=\"left\"\talign", "align=\"${1:left}\"$0"),
				("align=\"right\"\talign", "align=\"${1:right}\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("padding\t@padding", "padding=\"$1\"$0"),
				("style\t@style", "style=\"$1\"$0"),
				("tabheight\t@tabheight", "tabheight=\"$1\"$0"),
				("tabposition\t@tabposition", "tabposition=\"$1\"$0")
			],
			'attributes': [
				"style",
				"name",
				"align",
				"tabposition",
				"type",
				"padding",
				"tabheight"
			]
		}
		self.completions['cflayoutarea'] = {
			'completions': [
				("position\t@position", "position=\"$1\"$0"),
				("position=\"bottom\"\tposition", "position=\"${1:bottom}\"$0"),
				("position=\"center\"\tposition", "position=\"${1:center}\"$0"),
				("position=\"left\"\tposition", "position=\"${1:left}\"$0"),
				("position=\"right\"\tposition", "position=\"${1:right}\"$0"),
				("position=\"top\"\tposition", "position=\"${1:top}\"$0"),
				("align\t@align", "align=\"$1\"$0"),
				("align=\"center\"\talign", "align=\"${1:center}\"$0"),
				("align=\"justify\"\talign", "align=\"${1:justify}\"$0"),
				("align=\"left\"\talign", "align=\"${1:left}\"$0"),
				("align=\"right\"\talign", "align=\"${1:right}\"$0"),
				("closable\t@closable", "closable=\"$1\"$0"),
				("closable=\"true\"\tclosable", "closable=\"${1:true}\"$0"),
				("closable=\"false\"\tclosable", "closable=\"${1:false}\"$0"),
				("collapsible\t@collapsible", "collapsible=\"$1\"$0"),
				("collapsible=\"true\"\tcollapsible", "collapsible=\"${1:true}\"$0"),
				("collapsible=\"false\"\tcollapsible", "collapsible=\"${1:false}\"$0"),
				("disabled\t@disabled", "disabled=\"$1\"$0"),
				("disabled=\"true\"\tdisabled", "disabled=\"${1:true}\"$0"),
				("disabled=\"false\"\tdisabled", "disabled=\"${1:false}\"$0"),
				("initCollapsed\t@initCollapsed", "initCollapsed=\"$1\"$0"),
				("initCollapsed=\"true\"\tinitCollapsed", "initCollapsed=\"${1:true}\"$0"),
				("initCollapsed=\"false\"\tinitCollapsed", "initCollapsed=\"${1:false}\"$0"),
				("initHide\t@initHide", "initHide=\"$1\"$0"),
				("initHide=\"true\"\tinitHide", "initHide=\"${1:true}\"$0"),
				("initHide=\"false\"\tinitHide", "initHide=\"${1:false}\"$0"),
				("maxSize\t@maxSize", "maxSize=\"$1\"$0"),
				("minSize\t@minSize", "minSize=\"$1\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("onBindError\t@onBindError", "onBindError=\"$1\"$0"),
				("overflow\t@overflow", "overflow=\"$1\"$0"),
				("overflow=\"auto\"\toverflow", "overflow=\"${1:auto}\"$0"),
				("overflow=\"hidden\"\toverflow", "overflow=\"${1:hidden}\"$0"),
				("overflow=\"scroll\"\toverflow", "overflow=\"${1:scroll}\"$0"),
				("overflow=\"visible\"\toverflow", "overflow=\"${1:visible}\"$0"),
				("selected\t@selected", "selected=\"$1\"$0"),
				("selected=\"true\"\tselected", "selected=\"${1:true}\"$0"),
				("selected=\"false\"\tselected", "selected=\"${1:false}\"$0"),
				("size\t@size", "size=\"$1\"$0"),
				("source\t@source", "source=\"$1\"$0"),
				("splitter\t@splitter", "splitter=\"$1\"$0"),
				("splitter=\"true\"\tsplitter", "splitter=\"${1:true}\"$0"),
				("splitter=\"false\"\tsplitter", "splitter=\"${1:false}\"$0"),
				("style\t@style", "style=\"$1\"$0"),
				("title\t@title", "title=\"$1\"$0"),
				("refreshonactivate\t@refreshonactivate", "refreshonactivate=\"$1\"$0"),
				("refreshonactivate=\"true\"\trefreshonactivate", "refreshonactivate=\"${1:true}\"$0"),
				("refreshonactivate=\"false\"\trefreshonactivate", "refreshonactivate=\"${1:false}\"$0")
			],
			'attributes': [
				"minSize",
				"name",
				"refreshonactivate",
				"overflow",
				"closable",
				"disabled",
				"style",
				"source",
				"splitter",
				"align",
				"selected",
				"initHide",
				"initCollapsed",
				"collapsible",
				"onBindError",
				"size",
				"maxSize",
				"position",
				"title"
			]
		}
		self.completions['cfmail'] = {
			'completions': [
				("to\t@to", "to=\"$1\"$0"),
				("from\t@from", "from=\"$1\"$0"),
				("cc\t@cc", "cc=\"$1\"$0"),
				("bcc\t@bcc", "bcc=\"$1\"$0"),
				("subject\t@subject", "subject=\"$1\"$0"),
				("replyto\t@replyto", "replyto=\"$1\"$0"),
				("failto\t@failto", "failto=\"$1\"$0"),
				("username\t@username", "username=\"$1\"$0"),
				("password\t@password", "password=\"$1\"$0"),
				("wraptext\t@wraptext", "wraptext=\"$1\"$0"),
				("charset\t@charset", "charset=\"$1\"$0"),
				("charset=\"utf-8\"\tcharset", "charset=\"${1:utf-8}\"$0"),
				("charset=\"iso-8859-1\"\tcharset", "charset=\"${1:iso-8859-1}\"$0"),
				("charset=\"windows-1252\"\tcharset", "charset=\"${1:windows-1252}\"$0"),
				("charset=\"us-ascii\"\tcharset", "charset=\"${1:us-ascii}\"$0"),
				("charset=\"shift_jis\"\tcharset", "charset=\"${1:shift_jis}\"$0"),
				("charset=\"iso-2022-jp\"\tcharset", "charset=\"${1:iso-2022-jp}\"$0"),
				("charset=\"euc-jp\"\tcharset", "charset=\"${1:euc-jp}\"$0"),
				("charset=\"euc-kr\"\tcharset", "charset=\"${1:euc-kr}\"$0"),
				("charset=\"big5\"\tcharset", "charset=\"${1:big5}\"$0"),
				("charset=\"euc-cn\"\tcharset", "charset=\"${1:euc-cn}\"$0"),
				("charset=\"utf-16\"\tcharset", "charset=\"${1:utf-16}\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"plain\"\ttype", "type=\"${1:plain}\"$0"),
				("type=\"html\"\ttype", "type=\"${1:html}\"$0"),
				("type=\"text\"\ttype", "type=\"${1:text}\"$0"),
				("type=\"text/html\"\ttype", "type=\"${1:text/html}\"$0"),
				("type=\"text/plain\"\ttype", "type=\"${1:text/plain}\"$0"),
				("mimeattach\t@mimeattach", "mimeattach=\"$1\"$0"),
				("query\t@query", "query=\"$1\"$0"),
				("group\t@group", "group=\"$1\"$0"),
				("groupcasesensitive\t@groupcasesensitive", "groupcasesensitive=\"$1\"$0"),
				("groupcasesensitive=\"true\"\tgroupcasesensitive", "groupcasesensitive=\"${1:true}\"$0"),
				("groupcasesensitive=\"false\"\tgroupcasesensitive", "groupcasesensitive=\"${1:false}\"$0"),
				("startrow\t@startrow", "startrow=\"$1\"$0"),
				("maxrows\t@maxrows", "maxrows=\"$1\"$0"),
				("server\t@server", "server=\"$1\"$0"),
				("port\t@port", "port=\"$1\"$0"),
				("mailerid\t@mailerid", "mailerid=\"$1\"$0"),
				("timeout\t@timeout", "timeout=\"$1\"$0"),
				("spoolenable\t@spoolenable", "spoolenable=\"$1\"$0"),
				("spoolenable=\"true\"\tspoolenable", "spoolenable=\"${1:true}\"$0"),
				("spoolenable=\"false\"\tspoolenable", "spoolenable=\"${1:false}\"$0"),
				("debug\t@debug", "debug=\"$1\"$0"),
				("debug=\"true\"\tdebug", "debug=\"${1:true}\"$0"),
				("debug=\"false\"\tdebug", "debug=\"${1:false}\"$0"),
				("priority\t@priority", "priority=\"$1\"$0"),
				("priority=\"highest\"\tpriority", "priority=\"${1:highest}\"$0"),
				("priority=\"urgent\"\tpriority", "priority=\"${1:urgent}\"$0"),
				("priority=\"normal\"\tpriority", "priority=\"${1:normal}\"$0"),
				("priority=\"low\"\tpriority", "priority=\"${1:low}\"$0"),
				("priority=\"lowest\"\tpriority", "priority=\"${1:lowest}\"$0"),
				("usessl\t@usessl", "usessl=\"$1\"$0"),
				("usessl=\"true\"\tusessl", "usessl=\"${1:true}\"$0"),
				("usessl=\"false\"\tusessl", "usessl=\"${1:false}\"$0"),
				("usetls\t@usetls", "usetls=\"$1\"$0"),
				("usetls=\"true\"\tusetls", "usetls=\"${1:true}\"$0"),
				("usetls=\"false\"\tusetls", "usetls=\"${1:false}\"$0")
			],
			'attributes': [
				"subject",
				"mimeattach",
				"to",
				"maxrows",
				"groupcasesensitive",
				"port",
				"charset",
				"spoolenable",
				"wraptext",
				"password",
				"usetls",
				"type",
				"server",
				"debug",
				"group",
				"priority",
				"mailerid",
				"bcc",
				"query",
				"usessl",
				"cc",
				"startrow",
				"from",
				"username",
				"replyto",
				"failto",
				"timeout"
			]
		}
		self.completions['cfproperty'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"any\"\ttype", "type=\"${1:any}\"$0"),
				("type=\"array\"\ttype", "type=\"${1:array}\"$0"),
				("type=\"binary\"\ttype", "type=\"${1:binary}\"$0"),
				("type=\"boolean\"\ttype", "type=\"${1:boolean}\"$0"),
				("type=\"date\"\ttype", "type=\"${1:date}\"$0"),
				("type=\"guid\"\ttype", "type=\"${1:guid}\"$0"),
				("type=\"numeric\"\ttype", "type=\"${1:numeric}\"$0"),
				("type=\"query\"\ttype", "type=\"${1:query}\"$0"),
				("type=\"string\"\ttype", "type=\"${1:string}\"$0"),
				("type=\"struct\"\ttype", "type=\"${1:struct}\"$0"),
				("type=\"uuid\"\ttype", "type=\"${1:uuid}\"$0"),
				("required\t@required", "required=\"$1\"$0"),
				("required=\"true\"\trequired", "required=\"${1:true}\"$0"),
				("required=\"false\"\trequired", "required=\"${1:false}\"$0"),
				("default\t@default", "default=\"$1\"$0"),
				("displayname\t@displayname", "displayname=\"$1\"$0"),
				("hint\t@hint", "hint=\"$1\"$0")
			],
			'attributes': [
				"hint",
				"displayname",
				"name",
				"type",
				"default",
				"required"
			]
		}
		self.completions['cfquery'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("datasource\t@datasource", "datasource=\"$1\"$0"),
				("dbtype\t@dbtype", "dbtype=\"$1\"$0"),
				("username\t@username", "username=\"$1\"$0"),
				("password\t@password", "password=\"$1\"$0"),
				("maxrows\t@maxrows", "maxrows=\"$1\"$0"),
				("blockfactor\t@blockfactor", "blockfactor=\"$1\"$0"),
				("timeout\t@timeout", "timeout=\"$1\"$0"),
				("cachedafter\t@cachedafter", "cachedafter=\"$1\"$0"),
				("cachedwithin\t@cachedwithin", "cachedwithin=\"$1\"$0"),
				("debug\t@debug", "debug=\"$1\"$0"),
				("debug=\"true\"\tdebug", "debug=\"${1:true}\"$0"),
				("debug=\"false\"\tdebug", "debug=\"${1:false}\"$0"),
				("result\t@result", "result=\"$1\"$0")
			],
			'attributes': [
				"maxrows",
				"result",
				"name",
				"datasource",
				"blockfactor",
				"cachedwithin",
				"username",
				"password",
				"dbtype",
				"debug",
				"cachedafter",
				"timeout"
			]
		}
		self.completions['cfregistry'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"getAll\"\taction", "action=\"${1:getAll}\"$0"),
				("action=\"get\"\taction", "action=\"${1:get}\"$0"),
				("action=\"set\"\taction", "action=\"${1:set}\"$0"),
				("action=\"delete\"\taction", "action=\"${1:delete}\"$0"),
				("branch\t@branch", "branch=\"$1\"$0"),
				("entry\t@entry", "entry=\"$1\"$0"),
				("variable\t@variable", "variable=\"$1\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"String\"\ttype", "type=\"${1:String}\"$0"),
				("type=\"dWord\"\ttype", "type=\"${1:dWord}\"$0"),
				("type=\"key\"\ttype", "type=\"${1:key}\"$0"),
				("type=\"Any\"\ttype", "type=\"${1:Any}\"$0"),
				("sort\t@sort", "sort=\"$1\"$0"),
				("sort=\"entry asc\"\tsort", "sort=\"${1:entry asc}\"$0"),
				("sort=\"entry desc\"\tsort", "sort=\"${1:entry desc}\"$0"),
				("sort=\"type asc\"\tsort", "sort=\"${1:type asc}\"$0"),
				("sort=\"type desc\"\tsort", "sort=\"${1:type desc}\"$0"),
				("sort=\"value asc\"\tsort", "sort=\"${1:value asc}\"$0"),
				("sort=\"value desc\"\tsort", "sort=\"${1:value desc}\"$0"),
				("directory\t@directory", "directory=\"$1\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("mode\t@mode", "mode=\"$1\"$0"),
				("newdirectory\t@newdirectory", "newdirectory=\"$1\"$0"),
				("value\t@value", "value=\"$1\"$0"),
				("recurse\t@recurse", "recurse=\"$1\"$0"),
				("recurse=\"true\"\trecurse", "recurse=\"${1:true}\"$0"),
				("recurse=\"false\"\trecurse", "recurse=\"${1:false}\"$0")
			],
			'attributes': [
				"sort",
				"directory",
				"name",
				"entry",
				"variable",
				"value",
				"recurse",
				"mode",
				"action",
				"newdirectory",
				"type",
				"branch"
			]
		}
		self.completions['cfsearch'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("collection\t@collection", "collection=\"$1\"$0"),
				("category\t@category", "category=\"$1\"$0"),
				("categorytree\t@categorytree", "categorytree=\"$1\"$0"),
				("status\t@status", "status=\"$1\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"simple\"\ttype", "type=\"${1:simple}\"$0"),
				("type=\"explicit\"\ttype", "type=\"${1:explicit}\"$0"),
				("type=\"internet\"\ttype", "type=\"${1:internet}\"$0"),
				("type=\"internet_basic\"\ttype", "type=\"${1:internet_basic}\"$0"),
				("type=\"natural\"\ttype", "type=\"${1:natural}\"$0"),
				("criteria\t@criteria", "criteria=\"$1\"$0"),
				("maxrows\t@maxrows", "maxrows=\"$1\"$0"),
				("startrow\t@startrow", "startrow=\"$1\"$0"),
				("suggestions\t@suggestions", "suggestions=\"$1\"$0"),
				("suggestions=\"always\"\tsuggestions", "suggestions=\"${1:always}\"$0"),
				("suggestions=\"never\"\tsuggestions", "suggestions=\"${1:never}\"$0"),
				("suggestions=\"5\"\tsuggestions", "suggestions=\"${1:5}\"$0"),
				("suggestions=\"10\"\tsuggestions", "suggestions=\"${1:10}\"$0"),
				("contextpassages\t@contextpassages", "contextpassages=\"$1\"$0"),
				("contextbytes\t@contextbytes", "contextbytes=\"$1\"$0"),
				("contexthighlightbegin\t@contexthighlightbegin", "contexthighlightbegin=\"$1\"$0"),
				("contexthighlightbegin=\"\"\tcontexthighlightbegin", "contexthighlightbegin=\"${1:}\"$0"),
				("contexthighlightbegin=\"\"\tcontexthighlightbegin", "contexthighlightbegin=\"${1:}\"$0"),
				("contexthighlightbegin=\"\"\tcontexthighlightbegin", "contexthighlightbegin=\"${1:}\"$0"),
				("contexthighlightend\t@contexthighlightend", "contexthighlightend=\"$1\"$0"),
				("contexthighlightend=\"\"\tcontexthighlightend", "contexthighlightend=\"${1:}\"$0"),
				("contexthighlightend=\"\"\tcontexthighlightend", "contexthighlightend=\"${1:}\"$0"),
				("contexthighlightend=\"\"\tcontexthighlightend", "contexthighlightend=\"${1:}\"$0"),
				("previouscriteria\t@previouscriteria", "previouscriteria=\"$1\"$0"),
				("language\t@language", "language=\"$1\"$0")
			],
			'attributes': [
				"name",
				"language",
				"previouscriteria",
				"categorytree",
				"status",
				"maxrows",
				"criteria",
				"contextpassages",
				"category",
				"contexthighlightend",
				"collection",
				"suggestions",
				"contexthighlightbegin",
				"startrow",
				"contextbytes",
				"type"
			]
		}
		self.completions['cfslider'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("label\t@label", "label=\"$1\"$0"),
				("range\t@range", "range=\"$1\"$0"),
				("scale\t@scale", "scale=\"$1\"$0"),
				("value\t@value", "value=\"$1\"$0"),
				("onvalidate\t@onvalidate", "onvalidate=\"$1\"$0"),
				("message\t@message", "message=\"$1\"$0"),
				("onerror\t@onerror", "onerror=\"$1\"$0"),
				("height\t@height", "height=\"$1\"$0"),
				("width\t@width", "width=\"$1\"$0"),
				("vspace\t@vspace", "vspace=\"$1\"$0"),
				("hspace\t@hspace", "hspace=\"$1\"$0"),
				("align\t@align", "align=\"$1\"$0"),
				("align=\"top\"\talign", "align=\"${1:top}\"$0"),
				("align=\"left\"\talign", "align=\"${1:left}\"$0"),
				("align=\"bottom\"\talign", "align=\"${1:bottom}\"$0"),
				("align=\"baseline\"\talign", "align=\"${1:baseline}\"$0"),
				("align=\"texttop\"\talign", "align=\"${1:texttop}\"$0"),
				("align=\"absbottom\"\talign", "align=\"${1:absbottom}\"$0"),
				("align=\"middle\"\talign", "align=\"${1:middle}\"$0"),
				("align=\"absmiddle\"\talign", "align=\"${1:absmiddle}\"$0"),
				("align=\"right\"\talign", "align=\"${1:right}\"$0"),
				("lookandfeel\t@lookandfeel", "lookandfeel=\"$1\"$0"),
				("lookandfeel=\"motif\"\tlookandfeel", "lookandfeel=\"${1:motif}\"$0"),
				("lookandfeel=\"windows\"\tlookandfeel", "lookandfeel=\"${1:windows}\"$0"),
				("lookandfeel=\"metal\"\tlookandfeel", "lookandfeel=\"${1:metal}\"$0"),
				("vertical\t@vertical", "vertical=\"$1\"$0"),
				("vertical=\"true\"\tvertical", "vertical=\"${1:true}\"$0"),
				("vertical=\"false\"\tvertical", "vertical=\"${1:false}\"$0"),
				("bgcolor\t@bgcolor", "bgcolor=\"$1\"$0"),
				("bgcolor=\"black\"\tbgcolor", "bgcolor=\"${1:black}\"$0"),
				("bgcolor=\"red\"\tbgcolor", "bgcolor=\"${1:red}\"$0"),
				("bgcolor=\"blue\"\tbgcolor", "bgcolor=\"${1:blue}\"$0"),
				("bgcolor=\"magenta\"\tbgcolor", "bgcolor=\"${1:magenta}\"$0"),
				("bgcolor=\"cyan\"\tbgcolor", "bgcolor=\"${1:cyan}\"$0"),
				("bgcolor=\"orange\"\tbgcolor", "bgcolor=\"${1:orange}\"$0"),
				("bgcolor=\"darkgray\"\tbgcolor", "bgcolor=\"${1:darkgray}\"$0"),
				("bgcolor=\"pink\"\tbgcolor", "bgcolor=\"${1:pink}\"$0"),
				("bgcolor=\"gray\"\tbgcolor", "bgcolor=\"${1:gray}\"$0"),
				("bgcolor=\"white\"\tbgcolor", "bgcolor=\"${1:white}\"$0"),
				("bgcolor=\"lightgray\"\tbgcolor", "bgcolor=\"${1:lightgray}\"$0"),
				("bgcolor=\"yellow\"\tbgcolor", "bgcolor=\"${1:yellow}\"$0"),
				("textcolor\t@textcolor", "textcolor=\"$1\"$0"),
				("textcolor=\"black\"\ttextcolor", "textcolor=\"${1:black}\"$0"),
				("textcolor=\"red\"\ttextcolor", "textcolor=\"${1:red}\"$0"),
				("textcolor=\"blue\"\ttextcolor", "textcolor=\"${1:blue}\"$0"),
				("textcolor=\"magenta\"\ttextcolor", "textcolor=\"${1:magenta}\"$0"),
				("textcolor=\"cyan\"\ttextcolor", "textcolor=\"${1:cyan}\"$0"),
				("textcolor=\"orange\"\ttextcolor", "textcolor=\"${1:orange}\"$0"),
				("textcolor=\"darkgray\"\ttextcolor", "textcolor=\"${1:darkgray}\"$0"),
				("textcolor=\"pink\"\ttextcolor", "textcolor=\"${1:pink}\"$0"),
				("textcolor=\"gray\"\ttextcolor", "textcolor=\"${1:gray}\"$0"),
				("textcolor=\"white\"\ttextcolor", "textcolor=\"${1:white}\"$0"),
				("textcolor=\"lightgray\"\ttextcolor", "textcolor=\"${1:lightgray}\"$0"),
				("textcolor=\"yellow\"\ttextcolor", "textcolor=\"${1:yellow}\"$0"),
				("font\t@font", "font=\"$1\"$0"),
				("font=\"arial\"\tfont", "font=\"${1:arial}\"$0"),
				("font=\"times\"\tfont", "font=\"${1:times}\"$0"),
				("font=\"courier\"\tfont", "font=\"${1:courier}\"$0"),
				("font=\"arialunicodeMS\"\tfont", "font=\"${1:arialunicodeMS}\"$0"),
				("fontsize\t@fontsize", "fontsize=\"$1\"$0"),
				("italic\t@italic", "italic=\"$1\"$0"),
				("italic=\"true\"\titalic", "italic=\"${1:true}\"$0"),
				("italic=\"false\"\titalic", "italic=\"${1:false}\"$0"),
				("bold\t@bold", "bold=\"$1\"$0"),
				("bold=\"true\"\tbold", "bold=\"${1:true}\"$0"),
				("bold=\"false\"\tbold", "bold=\"${1:false}\"$0"),
				("notsupported\t@notsupported", "notsupported=\"$1\"$0")
			],
			'attributes': [
				"bgcolor",
				"name",
				"scale",
				"bold",
				"label",
				"height",
				"lookandfeel",
				"vertical",
				"fontsize",
				"onvalidate",
				"width",
				"notsupported",
				"textcolor",
				"message",
				"range",
				"italic",
				"font",
				"align",
				"value",
				"onerror",
				"vspace",
				"hspace"
			]
		}
		self.completions['cftextarea'] = {
			'completions': [
				("name\t@name", "name=\"$1\"$0"),
				("label\t@label", "label=\"$1\"$0"),
				("style\t@style", "style=\"$1\"$0"),
				("required\t@required", "required=\"$1\"$0"),
				("required=\"true\"\trequired", "required=\"${1:true}\"$0"),
				("required=\"false\"\trequired", "required=\"${1:false}\"$0"),
				("html\t@html", "html=\"$1\"$0"),
				("html=\"true\"\thtml", "html=\"${1:true}\"$0"),
				("html=\"false\"\thtml", "html=\"${1:false}\"$0"),
				("validate\t@validate", "validate=\"$1\"$0"),
				("validateat\t@validateat", "validateat=\"$1\"$0"),
				("validateat=\"onSubmit\"\tvalidateat", "validateat=\"${1:onSubmit}\"$0"),
				("validateat=\"onServer\"\tvalidateat", "validateat=\"${1:onServer}\"$0"),
				("validateat=\"onBlur\"\tvalidateat", "validateat=\"${1:onBlur}\"$0"),
				("message\t@message", "message=\"$1\"$0"),
				("range\t@range", "range=\"$1\"$0"),
				("maxlength\t@maxlength", "maxlength=\"$1\"$0"),
				("pattern\t@pattern", "pattern=\"$1\"$0"),
				("onvalidate\t@onvalidate", "onvalidate=\"$1\"$0"),
				("onerror\t@onerror", "onerror=\"$1\"$0"),
				("disabled\t@disabled", "disabled=\"$1\"$0"),
				("disabled=\"true\"\tdisabled", "disabled=\"${1:true}\"$0"),
				("disabled=\"false\"\tdisabled", "disabled=\"${1:false}\"$0"),
				("value\t@value", "value=\"$1\"$0"),
				("bind\t@bind", "bind=\"$1\"$0"),
				("onkeyup\t@onkeyup", "onkeyup=\"$1\"$0"),
				("onkeydown\t@onkeydown", "onkeydown=\"$1\"$0"),
				("onmouseup\t@onmouseup", "onmouseup=\"$1\"$0"),
				("onmousedown\t@onmousedown", "onmousedown=\"$1\"$0"),
				("onchange\t@onchange", "onchange=\"$1\"$0"),
				("onclick\t@onclick", "onclick=\"$1\"$0"),
				("enabled\t@enabled", "enabled=\"$1\"$0"),
				("enabled=\"true\"\tenabled", "enabled=\"${1:true}\"$0"),
				("enabled=\"false\"\tenabled", "enabled=\"${1:false}\"$0"),
				("visible\t@visible", "visible=\"$1\"$0"),
				("visible=\"true\"\tvisible", "visible=\"${1:true}\"$0"),
				("visible=\"false\"\tvisible", "visible=\"${1:false}\"$0"),
				("tooltip\t@tooltip", "tooltip=\"$1\"$0"),
				("height\t@height", "height=\"$1\"$0"),
				("width\t@width", "width=\"$1\"$0"),
				("basepath\t@basepath", "basepath=\"$1\"$0"),
				("bindattribute\t@bindattribute", "bindattribute=\"$1\"$0"),
				("bindonload\t@bindonload", "bindonload=\"$1\"$0"),
				("bindonload=\"true\"\tbindonload", "bindonload=\"${1:true}\"$0"),
				("bindonload=\"false\"\tbindonload", "bindonload=\"${1:false}\"$0"),
				("fontformats\t@fontformats", "fontformats=\"$1\"$0"),
				("fontnames\t@fontnames", "fontnames=\"$1\"$0"),
				("fontsizes\t@fontsizes", "fontsizes=\"$1\"$0"),
				("onbinderror\t@onbinderror", "onbinderror=\"$1\"$0"),
				("richtext\t@richtext", "richtext=\"$1\"$0"),
				("richtext=\"true\"\trichtext", "richtext=\"${1:true}\"$0"),
				("richtext=\"false\"\trichtext", "richtext=\"${1:false}\"$0"),
				("skin\t@skin", "skin=\"$1\"$0"),
				("skin=\"default\"\tskin", "skin=\"${1:default}\"$0"),
				("skin=\"silver\"\tskin", "skin=\"${1:silver}\"$0"),
				("skin=\"office2003\"\tskin", "skin=\"${1:office2003}\"$0"),
				("wrap\t@wrap", "wrap=\"$1\"$0"),
				("wrap=\"hard\"\twrap", "wrap=\"${1:hard}\"$0"),
				("wrap=\"off\"\twrap", "wrap=\"${1:off}\"$0"),
				("wrap=\"physical\"\twrap", "wrap=\"${1:physical}\"$0"),
				("wrap=\"virtual\"\twrap", "wrap=\"${1:virtual}\"$0"),
				("wrap=\"soft\"\twrap", "wrap=\"${1:soft}\"$0"),
				("sourcefortooltip\t@sourcefortooltip", "sourcefortooltip=\"$1\"$0"),
				("stylesxml\t@stylesxml", "stylesxml=\"$1\"$0"),
				("templatesxml\t@templatesxml", "templatesxml=\"$1\"$0"),
				("toolbar\t@toolbar", "toolbar=\"$1\"$0"),
				("toolbaronfocus\t@toolbaronfocus", "toolbaronfocus=\"$1\"$0"),
				("toolbaronfocus=\"true\"\ttoolbaronfocus", "toolbaronfocus=\"${1:true}\"$0"),
				("toolbaronfocus=\"false\"\ttoolbaronfocus", "toolbaronfocus=\"${1:false}\"$0")
			],
			'attributes': [
				"tooltip",
				"validateat",
				"height",
				"stylesxml",
				"bindonload",
				"disabled",
				"onvalidate",
				"visible",
				"range",
				"onchange",
				"html",
				"onerror",
				"required",
				"value",
				"onmousedown",
				"onbinderror",
				"fontsizes",
				"bindattribute",
				"skin",
				"sourcefortooltip",
				"onmouseup",
				"pattern",
				"richtext",
				"fontformats",
				"toolbaronfocus",
				"name",
				"onkeyup",
				"onkeydown",
				"label",
				"basepath",
				"bind",
				"toolbar",
				"validate",
				"width",
				"maxlength",
				"style",
				"onclick",
				"message",
				"enabled",
				"templatesxml",
				"fontnames",
				"wrap"
			]
		}
		self.completions['cftransaction'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"begin\"\taction", "action=\"${1:begin}\"$0"),
				("action=\"commit\"\taction", "action=\"${1:commit}\"$0"),
				("action=\"rollback\"\taction", "action=\"${1:rollback}\"$0"),
				("action=\"setsavepoint\"\taction", "action=\"${1:setsavepoint}\"$0"),
				("isolation\t@isolation", "isolation=\"$1\"$0"),
				("isolation=\"read_uncommitted\"\tisolation", "isolation=\"${1:read_uncommitted}\"$0"),
				("isolation=\"read_committed\"\tisolation", "isolation=\"${1:read_committed}\"$0"),
				("isolation=\"repeatable_read\"\tisolation", "isolation=\"${1:repeatable_read}\"$0"),
				("isolation=\"serializable\"\tisolation", "isolation=\"${1:serializable}\"$0"),
				("savepoint\t@savepoint", "savepoint=\"$1\"$0")
			],
			'attributes': [
				"action",
				"isolation",
				"savepoint"
			]
		}
		self.completions['cfwindow'] = {
			'completions': [
				("bodyStyle\t@bodyStyle", "bodyStyle=\"$1\"$0"),
				("center\t@center", "center=\"$1\"$0"),
				("center=\"true\"\tcenter", "center=\"${1:true}\"$0"),
				("center=\"false\"\tcenter", "center=\"${1:false}\"$0"),
				("closable\t@closable", "closable=\"$1\"$0"),
				("closable=\"true\"\tclosable", "closable=\"${1:true}\"$0"),
				("closable=\"false\"\tclosable", "closable=\"${1:false}\"$0"),
				("draggable\t@draggable", "draggable=\"$1\"$0"),
				("draggable=\"true\"\tdraggable", "draggable=\"${1:true}\"$0"),
				("draggable=\"false\"\tdraggable", "draggable=\"${1:false}\"$0"),
				("headerStyle\t@headerStyle", "headerStyle=\"$1\"$0"),
				("height\t@height", "height=\"$1\"$0"),
				("initShow\t@initShow", "initShow=\"$1\"$0"),
				("initShow=\"true\"\tinitShow", "initShow=\"${1:true}\"$0"),
				("initShow=\"false\"\tinitShow", "initShow=\"${1:false}\"$0"),
				("minHeight\t@minHeight", "minHeight=\"$1\"$0"),
				("minWidth\t@minWidth", "minWidth=\"$1\"$0"),
				("modal\t@modal", "modal=\"$1\"$0"),
				("modal=\"true\"\tmodal", "modal=\"${1:true}\"$0"),
				("modal=\"false\"\tmodal", "modal=\"${1:false}\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("onBindError\t@onBindError", "onBindError=\"$1\"$0"),
				("resizable\t@resizable", "resizable=\"$1\"$0"),
				("resizable=\"true\"\tresizable", "resizable=\"${1:true}\"$0"),
				("resizable=\"false\"\tresizable", "resizable=\"${1:false}\"$0"),
				("source\t@source", "source=\"$1\"$0"),
				("title\t@title", "title=\"$1\"$0"),
				("width\t@width", "width=\"$1\"$0"),
				("x\t@x", "x=\"$1\"$0"),
				("y\t@y", "y=\"$1\"$0"),
				("refreshonshow\t@refreshonshow", "refreshonshow=\"$1\"$0"),
				("refreshonshow=\"true\"\trefreshonshow", "refreshonshow=\"${1:true}\"$0"),
				("refreshonshow=\"false\"\trefreshonshow", "refreshonshow=\"${1:false}\"$0")
			],
			'attributes': [
				"name",
				"resizable",
				"minHeight",
				"height",
				"closable",
				"modal",
				"width",
				"initShow",
				"source",
				"draggable",
				"refreshonshow",
				"bodyStyle",
				"onBindError",
				"minWidth",
				"y",
				"x",
				"center",
				"headerStyle",
				"title"
			]
		}
		self.completions['cftooltip'] = {
			'completions': [
				("preventoverlap\t@preventoverlap", "preventoverlap=\"$1\"$0"),
				("preventoverlap=\"true\"\tpreventoverlap", "preventoverlap=\"${1:true}\"$0"),
				("preventoverlap=\"false\"\tpreventoverlap", "preventoverlap=\"${1:false}\"$0"),
				("autodismissdelay\t@autodismissdelay", "autodismissdelay=\"$1\"$0"),
				("hidedelay\t@hidedelay", "hidedelay=\"$1\"$0"),
				("showdelay\t@showdelay", "showdelay=\"$1\"$0"),
				("sourcefortooltip\t@sourcefortooltip", "sourcefortooltip=\"$1\"$0"),
				("tooltip\t@tooltip", "tooltip=\"$1\"$0")
			],
			'attributes': [
				"autodismissdelay",
				"preventoverlap",
				"hidedelay",
				"tooltip",
				"showdelay",
				"sourcefortooltip"
			]
		}
		self.completions['cffeed'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("columnmap\t@columnmap", "columnmap=\"$1\"$0"),
				("enclosureDir\t@enclosureDir", "enclosureDir=\"$1\"$0"),
				("ignoreEnclosureError\t@ignoreEnclosureError", "ignoreEnclosureError=\"$1\"$0"),
				("ignoreEnclosureError=\"true\"\tignoreEnclosureError", "ignoreEnclosureError=\"${1:true}\"$0"),
				("ignoreEnclosureError=\"false\"\tignoreEnclosureError", "ignoreEnclosureError=\"${1:false}\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("outputFile\t@outputFile", "outputFile=\"$1\"$0"),
				("overwrite\t@overwrite", "overwrite=\"$1\"$0"),
				("overwrite=\"true\"\toverwrite", "overwrite=\"${1:true}\"$0"),
				("overwrite=\"false\"\toverwrite", "overwrite=\"${1:false}\"$0"),
				("overWriteEnclosure\t@overWriteEnclosure", "overWriteEnclosure=\"$1\"$0"),
				("overWriteEnclosure=\"true\"\toverWriteEnclosure", "overWriteEnclosure=\"${1:true}\"$0"),
				("overWriteEnclosure=\"false\"\toverWriteEnclosure", "overWriteEnclosure=\"${1:false}\"$0"),
				("properties\t@properties", "properties=\"$1\"$0"),
				("query\t@query", "query=\"$1\"$0"),
				("source\t@source", "source=\"$1\"$0"),
				("timeout\t@timeout", "timeout=\"$1\"$0"),
				("proxyServer\t@proxyServer", "proxyServer=\"$1\"$0"),
				("xmlvar\t@xmlvar", "xmlvar=\"$1\"$0"),
				("proxyPort\t@proxyPort", "proxyPort=\"$1\"$0"),
				("proxyPassword\t@proxyPassword", "proxyPassword=\"$1\"$0"),
				("userAgent\t@userAgent", "userAgent=\"$1\"$0"),
				("proxyUser\t@proxyUser", "proxyUser=\"$1\"$0")
			],
			'attributes': [
				"ignoreEnclosureError",
				"userAgent",
				"name",
				"proxyPort",
				"overwrite",
				"proxyPassword",
				"properties",
				"columnmap",
				"enclosureDir",
				"proxyUser",
				"query",
				"source",
				"overWriteEnclosure",
				"outputFile",
				"xmlvar",
				"action",
				"proxyServer",
				"timeout"
			]
		}
		self.completions['cfpdf'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"addwatermark\"\taction", "action=\"${1:addwatermark}\"$0"),
				("action=\"deletepages\"\taction", "action=\"${1:deletepages}\"$0"),
				("action=\"getinfo\"\taction", "action=\"${1:getinfo}\"$0"),
				("action=\"merge\"\taction", "action=\"${1:merge}\"$0"),
				("action=\"protect\"\taction", "action=\"${1:protect}\"$0"),
				("action=\"processddx\"\taction", "action=\"${1:processddx}\"$0"),
				("action=\"read\"\taction", "action=\"${1:read}\"$0"),
				("action=\"removewatermark\"\taction", "action=\"${1:removewatermark}\"$0"),
				("action=\"setinfo\"\taction", "action=\"${1:setinfo}\"$0"),
				("action=\"thumbnail\"\taction", "action=\"${1:thumbnail}\"$0"),
				("action=\"write\"\taction", "action=\"${1:write}\"$0"),
				("ascending\t@ascending", "ascending=\"$1\"$0"),
				("ascending=\"true\"\tascending", "ascending=\"${1:true}\"$0"),
				("ascending=\"false\"\tascending", "ascending=\"${1:false}\"$0"),
				("copyfrom\t@copyfrom", "copyfrom=\"$1\"$0"),
				("destination\t@destination", "destination=\"$1\"$0"),
				("directory\t@directory", "directory=\"$1\"$0"),
				("encrypt\t@encrypt", "encrypt=\"$1\"$0"),
				("encrypt=\"RC4_40\"\tencrypt", "encrypt=\"${1:RC4_40}\"$0"),
				("encrypt=\"RC4_128\"\tencrypt", "encrypt=\"${1:RC4_128}\"$0"),
				("encrypt=\"RC4_128M\"\tencrypt", "encrypt=\"${1:RC4_128M}\"$0"),
				("encrypt=\"AES_128\"\tencrypt", "encrypt=\"${1:AES_128}\"$0"),
				("encrypt=\"none\"\tencrypt", "encrypt=\"${1:none}\"$0"),
				("flatten\t@flatten", "flatten=\"$1\"$0"),
				("flatten=\"true\"\tflatten", "flatten=\"${1:true}\"$0"),
				("flatten=\"false\"\tflatten", "flatten=\"${1:false}\"$0"),
				("foreground\t@foreground", "foreground=\"$1\"$0"),
				("foreground=\"true\"\tforeground", "foreground=\"${1:true}\"$0"),
				("foreground=\"false\"\tforeground", "foreground=\"${1:false}\"$0"),
				("image\t@image", "image=\"$1\"$0"),
				("info\t@info", "info=\"$1\"$0"),
				("isBase64\t@isBase64", "isBase64=\"$1\"$0"),
				("isBase64=\"true\"\tisBase64", "isBase64=\"${1:true}\"$0"),
				("isBase64=\"false\"\tisBase64", "isBase64=\"${1:false}\"$0"),
				("keepbookmark\t@keepbookmark", "keepbookmark=\"$1\"$0"),
				("keepbookmark=\"true\"\tkeepbookmark", "keepbookmark=\"${1:true}\"$0"),
				("keepbookmark=\"false\"\tkeepbookmark", "keepbookmark=\"${1:false}\"$0"),
				("name\t@name", "name=\"$1\"$0"),
				("newownerpassword\t@newownerpassword", "newownerpassword=\"$1\"$0"),
				("newuserpassword\t@newuserpassword", "newuserpassword=\"$1\"$0"),
				("opacity\t@opacity", "opacity=\"$1\"$0"),
				("order\t@order", "order=\"$1\"$0"),
				("order=\"name\"\torder", "order=\"${1:name}\"$0"),
				("order=\"time\"\torder", "order=\"${1:time}\"$0"),
				("overwrite\t@overwrite", "overwrite=\"$1\"$0"),
				("overwrite=\"yes\"\toverwrite", "overwrite=\"${1:yes}\"$0"),
				("overwrite=\"no\"\toverwrite", "overwrite=\"${1:no}\"$0"),
				("password\t@password", "password=\"$1\"$0"),
				("permissions\t@permissions", "permissions=\"$1\"$0"),
				("permissions=\"all\"\tpermissions", "permissions=\"${1:all}\"$0"),
				("permissions=\"allowassembly\"\tpermissions", "permissions=\"${1:allowassembly}\"$0"),
				("permissions=\"allowcopy\"\tpermissions", "permissions=\"${1:allowcopy}\"$0"),
				("permissions=\"AllowDegradedPrinting\"\tpermissions", "permissions=\"${1:AllowDegradedPrinting}\"$0"),
				("permissions=\"AllowFillIn\"\tpermissions", "permissions=\"${1:AllowFillIn}\"$0"),
				("permissions=\"AllowModifyAnnotations\"\tpermissions", "permissions=\"${1:AllowModifyAnnotations}\"$0"),
				("permissions=\"AllowModifyContents\"\tpermissions", "permissions=\"${1:AllowModifyContents}\"$0"),
				("permissions=\"AllowPrinting\"\tpermissions", "permissions=\"${1:AllowPrinting}\"$0"),
				("permissions=\"AllowScreenReaders\"\tpermissions", "permissions=\"${1:AllowScreenReaders}\"$0"),
				("permissions=\"AllowSecure\"\tpermissions", "permissions=\"${1:AllowSecure}\"$0"),
				("permissions=\"none\"\tpermissions", "permissions=\"${1:none}\"$0"),
				("position\t@position", "position=\"$1\"$0"),
				("rotation\t@rotation", "rotation=\"$1\"$0"),
				("showonprint\t@showonprint", "showonprint=\"$1\"$0"),
				("showonprint=\"yes\"\tshowonprint", "showonprint=\"${1:yes}\"$0"),
				("showonprint=\"no\"\tshowonprint", "showonprint=\"${1:no}\"$0"),
				("source\t@source", "source=\"$1\"$0"),
				("type\t@type", "type=\"$1\"$0"),
				("type=\"attachment\"\ttype", "type=\"${1:attachment}\"$0"),
				("type=\"bookmark\"\ttype", "type=\"${1:bookmark}\"$0"),
				("type=\"watermark\"\ttype", "type=\"${1:watermark}\"$0"),
				("version\t@version", "version=\"$1\"$0"),
				("version=\"1.1\"\tversion", "version=\"${1:1.1}\"$0"),
				("version=\"1.2\"\tversion", "version=\"${1:1.2}\"$0"),
				("version=\"1.3\"\tversion", "version=\"${1:1.3}\"$0"),
				("version=\"1.4\"\tversion", "version=\"${1:1.4}\"$0"),
				("version=\"1.5\"\tversion", "version=\"${1:1.5}\"$0"),
				("version=\"1.6\"\tversion", "version=\"${1:1.6}\"$0"),
				("transparent\t@transparent", "transparent=\"$1\"$0"),
				("transparent=\"true\"\ttransparent", "transparent=\"${1:true}\"$0"),
				("transparent=\"false\"\ttransparent", "transparent=\"${1:false}\"$0"),
				("resolution\t@resolution", "resolution=\"$1\"$0"),
				("stoponerror\t@stoponerror", "stoponerror=\"$1\"$0"),
				("stoponerror=\"true\"\tstoponerror", "stoponerror=\"${1:true}\"$0"),
				("stoponerror=\"false\"\tstoponerror", "stoponerror=\"${1:false}\"$0"),
				("inputfiles\t@inputfiles", "inputfiles=\"$1\"$0"),
				("scale\t@scale", "scale=\"$1\"$0"),
				("imageprefix\t@imageprefix", "imageprefix=\"$1\"$0"),
				("outputfiles\t@outputfiles", "outputfiles=\"$1\"$0"),
				("pages\t@pages", "pages=\"$1\"$0"),
				("ddxfile\t@ddxfile", "ddxfile=\"$1\"$0"),
				("saveoption\t@saveoption", "saveoption=\"$1\"$0"),
				("saveoption=\"full\"\tsaveoption", "saveoption=\"${1:full}\"$0"),
				("saveoption=\"incremental\"\tsaveoption", "saveoption=\"${1:incremental}\"$0"),
				("saveoption=\"linear\"\tsaveoption", "saveoption=\"${1:linear}\"$0"),
				("format\t@format", "format=\"$1\"$0"),
				("format=\"jpg\"\tformat", "format=\"${1:jpg}\"$0"),
				("format=\"tiff\"\tformat", "format=\"${1:tiff}\"$0"),
				("format=\"png\"\tformat", "format=\"${1:png}\"$0")
			],
			'attributes': [
				"imageprefix",
				"overwrite",
				"destination",
				"order",
				"rotation",
				"isBase64",
				"resolution",
				"source",
				"version",
				"ascending",
				"newuserpassword",
				"info",
				"action",
				"password",
				"showonprint",
				"position",
				"type",
				"scale",
				"name",
				"permissions",
				"outputfiles",
				"stoponerror",
				"image",
				"keepbookmark",
				"encrypt",
				"ddxfile",
				"flatten",
				"saveoption",
				"copyfrom",
				"opacity",
				"transparent",
				"directory",
				"format",
				"pages",
				"inputfiles",
				"newownerpassword",
				"foreground"
			]
		}
		self.completions['cfpdfform'] = {
			'completions': [
				("action\t@action", "action=\"$1\"$0"),
				("action=\"populate\"\taction", "action=\"${1:populate}\"$0"),
				("action=\"read\"\taction", "action=\"${1:read}\"$0"),
				("datafile\t@datafile", "datafile=\"$1\"$0"),
				("destination\t@destination", "destination=\"$1\"$0"),
				("overwrite\t@overwrite", "overwrite=\"$1\"$0"),
				("overwrite=\"true\"\toverwrite", "overwrite=\"${1:true}\"$0"),
				("overwrite=\"false\"\toverwrite", "overwrite=\"${1:false}\"$0"),
				("overwritedata\t@overwritedata", "overwritedata=\"$1\"$0"),
				("overwritedata=\"true\"\toverwritedata", "overwritedata=\"${1:true}\"$0"),
				("overwritedata=\"false\"\toverwritedata", "overwritedata=\"${1:false}\"$0"),
				("result\t@result", "result=\"$1\"$0"),
				("source\t@source", "source=\"$1\"$0"),
				("xmldata\t@xmldata", "xmldata=\"$1\"$0"),
				("xmldata=\"true\"\txmldata", "xmldata=\"${1:true}\"$0"),
				("xmldata=\"false\"\txmldata", "xmldata=\"${1:false}\"$0")
			],
			'attributes': [
				"source",
				"result",
				"overwrite",
				"destination",
				"xmldata",
				"action",
				"overwritedata",
				"datafile"
			]
		}
		self.completions['cfpresentation'] = {
			'completions': [
				("backgroundColor\t@backgroundColor", "backgroundColor=\"$1\"$0"),
				("control\t@control", "control=\"$1\"$0"),
				("control=\"normal\"\tcontrol", "control=\"${1:normal}\"$0"),
				("control=\"brief\"\tcontrol", "control=\"${1:brief}\"$0"),
				("controlLocation\t@controlLocation", "controlLocation=\"$1\"$0"),
				("controlLocation=\"right\"\tcontrolLocation", "controlLocation=\"${1:right}\"$0"),
				("controlLocation=\"left\"\tcontrolLocation", "controlLocation=\"${1:left}\"$0"),
				("directory\t@directory", "directory=\"$1\"$0"),
				("glowColor\t@glowColor", "glowColor=\"$1\"$0"),
				("initialTab\t@initialTab", "initialTab=\"$1\"$0"),
				("initialTab=\"outline\"\tinitialTab", "initialTab=\"${1:outline}\"$0"),
				("initialTab=\"search\"\tinitialTab", "initialTab=\"${1:search}\"$0"),
				("initialTab=\"notes\"\tinitialTab", "initialTab=\"${1:notes}\"$0"),
				("lightColor\t@lightColor", "lightColor=\"$1\"$0"),
				("overwrite\t@overwrite", "overwrite=\"$1\"$0"),
				("overwrite=\"true\"\toverwrite", "overwrite=\"${1:true}\"$0"),
				("overwrite=\"false\"\toverwrite", "overwrite=\"${1:false}\"$0"),
				("primaryColor\t@primaryColor", "primaryColor=\"$1\"$0"),
				("shadowColor\t@shadowColor", "shadowColor=\"$1\"$0"),
				("showNotes\t@showNotes", "showNotes=\"$1\"$0"),
				("showNotes=\"true\"\tshowNotes", "showNotes=\"${1:true}\"$0"),
				("showNotes=\"false\"\tshowNotes", "showNotes=\"${1:false}\"$0"),
				("showOutline\t@showOutline", "showOutline=\"$1\"$0"),
				("showOutline=\"true\"\tshowOutline", "showOutline=\"${1:true}\"$0"),
				("showOutline=\"false\"\tshowOutline", "showOutline=\"${1:false}\"$0"),
				("showSearch\t@showSearch", "showSearch=\"$1\"$0"),
				("showSearch=\"true\"\tshowSearch", "showSearch=\"${1:true}\"$0"),
				("showSearch=\"false\"\tshowSearch", "showSearch=\"${1:false}\"$0"),
				("textColor\t@textColor", "textColor=\"$1\"$0"),
				("title\t@title", "title=\"$1\"$0"),
				("authpassword\t@authpassword", "authpassword=\"$1\"$0"),
				("authuser\t@authuser", "authuser=\"$1\"$0"),
				("autoplay\t@autoplay", "autoplay=\"$1\"$0"),
				("autoplay=\"true\"\tautoplay", "autoplay=\"${1:true}\"$0"),
				("autoplay=\"false\"\tautoplay", "autoplay=\"${1:false}\"$0"),
				("loop\t@loop", "loop=\"$1\"$0"),
				("loop=\"true\"\tloop", "loop=\"${1:true}\"$0"),
				("loop=\"false\"\tloop", "loop=\"${1:false}\"$0"),
				("proxypassword\t@proxypassword", "proxypassword=\"$1\"$0"),
				("proxyuser\t@proxyuser", "proxyuser=\"$1\"$0"),
				("proxyhost\t@proxyhost", "proxyhost=\"$1\"$0"),
				("proxyport\t@proxyport", "proxyport=\"$1\"$0"),
				("useragent\t@useragent", "useragent=\"$1\"$0")
			],
			'attributes': [
				"lightColor",
				"useragent",
				"proxyport",
				"overwrite",
				"proxypassword",
				"control",
				"showOutline",
				"glowColor",
				"proxyhost",
				"loop",
				"primaryColor",
				"proxyuser",
				"authuser",
				"textColor",
				"initialTab",
				"directory",
				"showSearch",
				"autoplay",
				"backgroundColor",
				"controlLocation",
				"showNotes",
				"authpassword",
				"shadowColor",
				"title"
			]
		}
		self.completions['cfpresentationslide'] = {
			'completions': [
				("audio\t@audio", "audio=\"$1\"$0"),
				("bottomMargin\t@bottomMargin", "bottomMargin=\"$1\"$0"),
				("duration\t@duration", "duration=\"$1\"$0"),
				("notes\t@notes", "notes=\"$1\"$0"),
				("presenter\t@presenter", "presenter=\"$1\"$0"),
				("rightMargin\t@rightMargin", "rightMargin=\"$1\"$0"),
				("scale\t@scale", "scale=\"$1\"$0"),
				("src\t@src", "src=\"$1\"$0"),
				("title\t@title", "title=\"$1\"$0"),
				("topMargin\t@topMargin", "topMargin=\"$1\"$0"),
				("video\t@video", "video=\"$1\"$0"),
				("advance\t@advance", "advance=\"$1\"$0"),
				("advance=\"auto\"\tadvance", "advance=\"${1:auto}\"$0"),
				("advance=\"never\"\tadvance", "advance=\"${1:never}\"$0"),
				("advance=\"click\"\tadvance", "advance=\"${1:click}\"$0"),
				("authpassword\t@authpassword", "authpassword=\"$1\"$0"),
				("authuser\t@authuser", "authuser=\"$1\"$0"),
				("marginbottom\t@marginbottom", "marginbottom=\"$1\"$0"),
				("marginleft\t@marginleft", "marginleft=\"$1\"$0"),
				("marginright\t@marginright", "marginright=\"$1\"$0"),
				("margintop\t@margintop", "margintop=\"$1\"$0"),
				("useragent\t@useragent", "useragent=\"$1\"$0")
			],
			'attributes': [
				"useragent",
				"scale",
				"advance",
				"audio",
				"video",
				"marginright",
				"src",
				"authuser",
				"presenter",
				"bottomMargin",
				"marginbottom",
				"margintop",
				"marginleft",
				"rightMargin",
				"authpassword",
				"topMargin",
				"duration",
				"notes",
				"title"
			]
		}
		del self.completions['cfprogressbar']
		del self.completions['cfspreadsheet']
		del self.completions['cfmediaplayer']
		del self.completions['cffileupload']
		del self.completions['cfsharepoint']
		del self.completions['cfmapitem']
		del self.completions['cfmap']

